#!/bin/bash
# this is a hook function for the kernel-creation phase
#
# htvcenter Enterprise developed by htvcenter Enterprise GmbH.
#
# All source code and content (c) Copyright 2014, htvcenter Enterprise GmbH unless specifically noted otherwise.
#
# This source code is released under the htvcenter Enterprise Server and Client License, unless otherwise agreed with htvcenter Enterprise GmbH.
# The latest version of this license can be found here: http://htvcenter-enterprise.com/license
#
# By using this software, you acknowledge having read this license and agree to be bound thereby.
#
#           http://htvcenter-enterprise.com
#
# Copyright 2014, htvcenter Enterprise GmbH <info@htvcenter-enterprise.com>
#

function iscsi_storage_kernel_hook() {

	local KERNEL_NAME=$1
	local KERNEL_VERSION=$2
	local KERNEL_LOCATION=$3
	local KERNEL_TYPE=$4

	echo "iscsi-storage-plugin: Running iscsi_storage_kernel_hook $KERNEL_NAME $KERNEL_VERSION $KERNEL_LOCATION $KERNEL_TYPE"
	echo "iscsi-storage-plugin: Running iscsi_storage_kernel_hook $KERNEL_NAME $KERNEL_VERSION $KERNEL_LOCATION $KERNEL_TYPE" | logger

	# try to find the iscsid + iscsiadm util fitting to the created kernel
	if [ -x "$KERNEL_LOCATION/sbin/iscsid" ]; then
		cp -a $KERNEL_LOCATION/sbin/iscsid $htvcenter_SERVER_BASE_DIR/htvcenter/web/boot-service/iscsid.$KERNEL_NAME
		echo "iscsi-storage-plugin: Found iscsid at $KERNEL_LOCATION/sbin/iscsid. Coping to $htvcenter_SERVER_BASE_DIR/htvcenter/web/boot-service/iscsid.$KERNEL_NAME"
		echo "iscsi-storage-plugin: Found iscsid at $KERNEL_LOCATION/sbin/iscsid. Coping to $htvcenter_SERVER_BASE_DIR/htvcenter/web/boot-service/iscsid.$KERNEL_NAME" | logger
	fi
	if [ -x "$KERNEL_LOCATION/usr/sbin/iscsid" ]; then
		cp -a $KERNEL_LOCATION/usr/sbin/iscsid $htvcenter_SERVER_BASE_DIR/htvcenter/web/boot-service/iscsid.$KERNEL_NAME
		echo "iscsi-storage-plugin: Found iscsid at $KERNEL_LOCATION/usr/sbin/iscsid. Coping to $htvcenter_SERVER_BASE_DIR/htvcenter/web/boot-service/iscsid.$KERNEL_NAME"
		echo "iscsi-storage-plugin: Found iscsid at $KERNEL_LOCATION/usr/sbin/iscsid. Coping to $htvcenter_SERVER_BASE_DIR/htvcenter/web/boot-service/iscsid.$KERNEL_NAME" | logger
	fi
	if [ -x "$KERNEL_LOCATION/sbin/iscsiadm" ]; then
		cp -a $KERNEL_LOCATION/sbin/iscsiadm $htvcenter_SERVER_BASE_DIR/htvcenter/web/boot-service/iscsiadm.$KERNEL_NAME
		echo "iscsi-storage-plugin: Found iscsiadm at $KERNEL_LOCATION/sbin/iscsiadm. Coping to $htvcenter_SERVER_BASE_DIR/htvcenter/web/boot-service/iscsiadm.$KERNEL_NAME"
		echo "iscsi-storage-plugin: Found iscsiadm at $KERNEL_LOCATION/sbin/iscsiadm. Coping to $htvcenter_SERVER_BASE_DIR/htvcenter/web/boot-service/iscsiadm.$KERNEL_NAME" | logger
	fi
	if [ -x "$KERNEL_LOCATION/usr/bin/iscsiadm" ]; then
		cp -a $KERNEL_LOCATION/usr/bin/iscsiadm $htvcenter_SERVER_BASE_DIR/htvcenter/web/boot-service/iscsiadm.$KERNEL_NAME
		echo "iscsi-storage-plugin: Found iscsiadm at $KERNEL_LOCATION/usr/bin/iscsiadm. Coping to $htvcenter_SERVER_BASE_DIR/htvcenter/web/boot-service/iscsiadm.$KERNEL_NAME"
		echo "iscsi-storage-plugin: Found iscsiadm at $KERNEL_LOCATION/usr/bin/iscsiadm. Coping to $htvcenter_SERVER_BASE_DIR/htvcenter/web/boot-service/iscsiadm.$KERNEL_NAME" | logger
	fi

}

