#!/bin/bash
# init script for the htvcenter nfs-storage-plugin
#
# htvcenter Enterprise developed by htvcenter Enterprise GmbH.
#
# All source code and content (c) Copyright 2014, htvcenter Enterprise GmbH unless specifically noted otherwise.
#
# This source code is released under the htvcenter Enterprise Server and Client License, unless otherwise agreed with htvcenter Enterprise GmbH.
# The latest version of this license can be found here: http://htvcenter-enterprise.com/license
#
# By using this software, you acknowledge having read this license and agree to be bound thereby.
#
#           http://htvcenter-enterprise.com
#
# Copyright 2014, htvcenter Enterprise GmbH <info@htvcenter-enterprise.com>
#

htvcenter_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
. $htvcenter_SERVER_BASE_DIR/htvcenter/etc/htvcenter-server.conf
. $htvcenter_SERVER_BASE_DIR/htvcenter/include/htvcenter-functions
. $htvcenter_SERVER_BASE_DIR/htvcenter/include/htvcenter-server-functions
. $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/nfs-storage/include/htvcenter-plugin-nfs-storage-functions
. $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/nfs-storage/etc/htvcenter-plugin-nfs-storage.conf



function htvcenter_plugin_nfs_storage_start() {
	echo "Starting the htvcenter nfs-storage-plugin"
	touch $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/base/plugins/nfs-storage/.running
	if [ "$NFS_STORAGE_AUTO_START" == "yes" ]; then
		if [ -x "/etc/init.d/portmap" ]; then
			if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
				invoke-rc.d portmap start
			else
				/etc/init.d/portmap start
			fi
		fi
		if [ -x "/etc/init.d/nfs-kernel-server" ]; then
			if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
				invoke-rc.d nfs-kernel-server start
			else
				/etc/init.d/nfs-kernel-server start
			fi
		fi


		if [ -x "/etc/init.d/nfs" ]; then
			if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
				invoke-rc.d nfs start
			else
				/etc/init.d/nfs start
			fi
		fi
		if [ -x "/etc/init.d/nfslock" ]; then
			if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
				invoke-rc.d nfslock start
			else
				/etc/init.d/nfslock start
			fi
		fi
		# for Suse
		if [ -x /etc/init.d/nfsserver ]; then
			/etc/init.d/nfsserver start
		fi
	fi
}


function htvcenter_plugin_nfs_storage_stop() {
	echo "Stopping the htvcenter nfs-storage-plugin"
	rm -f $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/base/plugins/nfs-storage/.running
	if [ "$NFS_STORAGE_AUTO_START" == "yes" ]; then
		if [ -x "/etc/init.d/nfs-kernel-server" ]; then
			if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
				invoke-rc.d nfs-kernel-server stop
			else
				/etc/init.d/nfs-kernel-server stop
			fi
		fi
		if [ -x "/etc/init.d/portmap" ]; then
			if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
				invoke-rc.d portmap stop
			else
				/etc/init.d/portmap stop
			fi
		fi

		if [ -x "/etc/init.d/nfs" ]; then
			if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
				invoke-rc.d nfs stop
			else
				/etc/init.d/nfs stop
			fi
		fi
		if [ -x "/etc/init.d/nfslock" ]; then
			if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
				invoke-rc.d nfslock stop
			else
				/etc/init.d/nfslock stop
			fi
		fi
		# for Suse
		if [ -x /etc/init.d/nfsserver ]; then
			/etc/init.d/nfsserver stop
		fi
	fi
}


function htvcenter_plugin_nfs_storage_uninstall() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "nfs-storage: Please give a username to uninstall the plugin : "
		read USERNAME
		echo
		echo -n "nfs-storage: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Uninstalling the htvcenter nfs-storage-plugin"
	htvcenter_plugin_nfs_storage_stop
	htvcenter_server_remove_deployment_type $USERNAME $PASSWORD nfs-deployment
	rm -f $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/base/plugins/nfs-storage
	rm -f $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/boot-service/root-mount.nfs-deployment
	rm -f $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/boot-service/image.nfs-deployment.php
	rm -f $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/boot-service/boot-service-nfs-storage.tgz
}

function htvcenter_plugin_nfs_storage_init() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "nfs-storage: Please give a username to init the plugin : "
		read USERNAME
		echo
		echo -n "nfs-storage: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Initializing the htvcenter nfs-storage-plugin"
	htvcenter_server_add_deployment_type $USERNAME $PASSWORD nfs-deployment nfs-deployment "Nfs-root deployment" nfs-storage "NFS Storage"
	# linking the web dir
	ln -sf $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/nfs-storage/web $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/base/plugins/nfs-storage
	# linking the boot-service
	ln -sf $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/nfs-storage/web/boot-service-nfs-storage.tgz $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/boot-service/boot-service-nfs-storage.tgz
	# linking the root mount hook
	chmod +x $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/nfs-storage/web/root-mount.nfs-deployment
	ln -s $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/nfs-storage/web/root-mount.nfs-deployment $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/boot-service/root-mount.nfs-deployment
	# linking the image-menu
	ln -sf $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/nfs-storage/web/image.nfs-deployment.php $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/boot-service/image.nfs-deployment.php
	# create storage dir for stat files
	mkdir -p $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/nfs-storage/web/storage
	chmod 777 $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/nfs-storage/web/storage
	echo "Order deny,allow" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/nfs-storage/web/storage/.htaccess
	echo "Deny from all" >> $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/nfs-storage/web/storage/.htaccess

}

USER=$2
PASS=$3

case "$1" in
	start)
		htvcenter_plugin_nfs_storage_start
		;;
	stop)
		htvcenter_plugin_nfs_storage_stop
		;;
	restart)
		htvcenter_plugin_nfs_storage_stop
		sleep 1
		htvcenter_plugin_nfs_storage_start
		;;
	init)
		htvcenter_plugin_nfs_storage_init $USER $PASS
		;;
	uninstall)
		htvcenter_plugin_nfs_storage_uninstall $USER $PASS
		;;
	*)
		echo "Usage: $0 {start|stop|restart|init|uninstall}"
		exit 1

esac
exit $?




