#!/bin/bash
# htvcenter db2-specfic functions
#
# htvcenter Enterprise developed by htvcenter Enterprise GmbH.
#
# All source code and content (c) Copyright 2014, htvcenter Enterprise GmbH unless specifically noted otherwise.
#
# This source code is released under the htvcenter Enterprise Server and Client License, unless otherwise agreed with htvcenter Enterprise GmbH.
# The latest version of this license can be found here: http://htvcenter-enterprise.com/license
#
# By using this software, you acknowledge having read this license and agree to be bound thereby.
#
#           http://htvcenter-enterprise.com
#
# Copyright 2014, htvcenter Enterprise GmbH <info@htvcenter-enterprise.com>
#

if [ "$htvcenter_SERVER_BASE_DIR" == "" ]; then
	echo "ERROR: Please export htvcenter_SERVER_BASE_DIR before sourcing $0"
	exit 1
fi

. $htvcenter_SERVER_BASE_DIR/htvcenter/etc/htvcenter-server.conf
htvcenter_DATABASE_INIT="$htvcenter_SERVER_BASE_DIR/htvcenter/etc/db/db2/htvcenter-db2-init.sql"


function initialize_database() {

	if ! which db2 1>/dev/null 2>&1; then
		echo "ERROR: DB2 client 'db2' not installed/found on this system"
		return 1
	else
		DB2_CLIENT=`which db2`
	fi

	echo "Initializing the htvcenter-database"
	cat $htvcenter_DATABASE_INIT |	\
		sed -e "s/connect to htvcenter_DB/connect to $htvcenter_DATABASE_NAME/g" |	\
		sed -e "s/htvcenter_SERVER_IP_ADDRESS/$htvcenter_SERVER_IP_ADDRESS/g"	\
		> /tmp/htvcenter-db2-init.sql
	chmod 777 /tmp/htvcenter-db2-init.sql
	su - $htvcenter_DATABASE_USER -c "$DB2_CLIENT -vf /tmp/htvcenter-db2-init.sql"
	rm -f /tmp/htvcenter-db2-init.sql
	# db2 client does not return good
	return 0

}


function backup_database() {
	local SQL=$1
	echo "Creating backup of the htvcenter-database at $SQL"
	echo "NOTICE: Backup for DB2 databases not yet implemented"
	return $RET

}

function restore_database() {
	local SQL=$1
	echo "Restoring the htvcenter-database from $SQL"
	echo "NOTICE: Restore for DB2 databases not yet implemented"
	return $RET

}

function drop_database() {
	echo "Dropping the htvcenter-database"
	echo "NOTICE: Drop for DB2 databases not yet implemented"
	return $RET
}

case "$1" in
	init)
		initialize_database
		;;
	backup)
		backup_database $2
		;;
	restore)
		restore_database $2
		;;
	drop)
		drop_database
		;;
esac
