#!/bin/bash
# init script for the htvcenter cloud-plugin
#
# htvcenter Enterprise developed by HTBase Corp.
#
# All source code and content (c) Copyright 2015, HTBase Corp unless specifically noted otherwise.
#
# This source code is released under the htvcenter Enterprise Server and Client License, unless otherwise agreed with htvcenter Enterprise.
#
# By using this software, you acknowledge having read this license and agree to be bound thereby.
#
#           http://www.htbase.com
#
# Copyright 2014, HTVBase Corp <bandrade@htbase.com>
#

htvcenter_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
. $htvcenter_SERVER_BASE_DIR/htvcenter/etc/htvcenter-server.conf
. $htvcenter_SERVER_BASE_DIR/htvcenter/include/htvcenter-functions
. $htvcenter_SERVER_BASE_DIR/htvcenter/include/htvcenter-server-functions
. $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/cloud/include/htvcenter-plugin-cloud-functions
. $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/cloud/etc/htvcenter-plugin-cloud.conf
htvcenter_server_get_config
export resource_htvcenterserver=$htvcenter_SERVER_IP_ADDRESS
# define wget to use with https
if [ "$htvcenter_WEB_PROTOCOL" == "https" ]; then
	WGET_NO_CERT_CHECK="--no-check-certificate"
fi


function htvcenter_plugin_cloud_start() {
	echo "Starting the htvcenter cloud-plugin"
	touch $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/base/plugins/cloud/.running
}


function htvcenter_plugin_cloud_stop() {
	echo "Stopping the htvcenter cloud-plugin"
	rm -f $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/base/plugins/cloud/.running
}

function htvcenter_plugin_cloud_uninstall() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "cloud: Please give a username to uninstall the plugin : "
		read USERNAME
		echo
		echo -n "cloud: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Uninstalling the htvcenter cloud-plugin"
	htvcenter_plugin_cloud_stop

	# removing the cloud tables
	if ! wget -q $WGET_NO_CERT_CHECK -O /dev/null --http-user=$USERNAME --http-password=$PASSWORD "$htvcenter_WEB_PROTOCOL://$resource_htvcenterserver/htvcenter/base/plugins/cloud/cloud-action.php?cloud_command=uninstall"; then
		cloud_manager_log uninstall "ERROR: Could not drop the cloud-plugin tables in the database!"
	fi
	# remove boot-service + soap-service
	rm -f $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/boot-service/boot-service-cloud.tgz
	rm -f $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/boot-service/cloudadmin.wdsl
	rm -f $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/boot-service/clouduser.wdsl
	rm -f $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/boot-service/cloudadmin.compat.wdsl
	rm -f $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/boot-service/clouduser.compat.wdsl
	# remove netconf dir
	rm -rf $htvcenter_SERVER_BASE_DIR/htvcenter/web/action/cloud-conf
	# remove auth files
	rm -f $htvcenter_WEBSERVER_DOCUMENT_ROOT/cloud-fortis/user/.htaccess
	rm -f $htvcenter_WEBSERVER_DOCUMENT_ROOT/cloud-fortis/user/.htpasswd
	# remove custom-icons
	rm -rf $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/cloud/cloud-fortis/web/user/custom-icons
	# remove the portal
	rm -f $htvcenter_WEBSERVER_DOCUMENT_ROOT/cloud-fortis
	rm -f $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/base/plugins/cloud
	rm -f $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/boot-service/boot-service-cloud.tgz
	if [ -f /etc/debian_version ]; then
		rm -f /etc/apache2/conf.d/htvcenter-cloud.conf
	elif [ -f /etc/redhat-release ]; then
		rm -f /etc/httpd/conf.d/htvcenter-cloud.conf
	elif [ -f /etc/SuSE-release ]; then
		rm -f /etc/apache2/conf.d/htvcenter-cloud.conf
		# remove the symlink we created at init
		if [ -h /usr/bin/htpasswd ]; then
			rm -f /usr/bin/htpasswd
		fi
	fi
	$htvcenter_WEBSERVER_INIT reload

	
}

function htvcenter_plugin_cloud_init() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "cloud: Please give a username to init the plugin : "
		read USERNAME
		echo
		echo -n "cloud: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Initializing the htvcenter cloud-plugin"
	# linking the web dir
	ln -sf $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/cloud/web $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/base/plugins/cloud

	# setup the wdsl definitions
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/cloud/web/soap/cloudadmin.wdsl	| \
		sed -e "s/@@htvcenter_SERVER_IP_ADDRESS@@/$htvcenter_SERVER_IP_ADDRESS/g" > $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/boot-service/cloudadmin.wdsl
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/cloud/cloud-fortis/web/user/soap/clouduser.wdsl	| \
		sed -e "s/@@htvcenter_SERVER_IP_ADDRESS@@/$htvcenter_SERVER_IP_ADDRESS/g" > $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/boot-service/clouduser.wdsl
	# compat webservices
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/cloud/web/soap/cloudadmin.compat.wdsl	| \
		sed -e "s/@@htvcenter_SERVER_IP_ADDRESS@@/$htvcenter_SERVER_IP_ADDRESS/g" > $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/boot-service/cloudadmin.compat.wdsl
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/cloud/cloud-fortis/web/user/soap/clouduser.compat.wdsl	| \
		sed -e "s/@@htvcenter_SERVER_IP_ADDRESS@@/$htvcenter_SERVER_IP_ADDRESS/g" > $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/boot-service/clouduser.compat.wdsl

	# link the web portal to the documentroot
	# create the virtualhost + auth for the cloud web portal
	if [ -f /etc/debian_version ]; then
		ln -sf $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/cloud/cloud-fortis/web/ $htvcenter_WEBSERVER_DOCUMENT_ROOT/cloud-fortis
		# the default apache config normally does not allow to override the authconfig (needed for basic auth)
		# so we allow it for the htvcenter directory
		cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/cloud/etc/httpd/htvcenter-httpd.conf | sed -e "s#htvcenter_WEBSERVER_DOCUMENT_ROOT#$htvcenter_WEBSERVER_DOCUMENT_ROOT#g" > /etc/apache2/conf.d/htvcenter-cloud.conf
	elif [ -f /etc/redhat-release ]; then
		ln -sf $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/cloud/cloud-fortis/web/ $htvcenter_WEBSERVER_DOCUMENT_ROOT/cloud-fortis
		cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/cloud/etc/httpd/htvcenter-httpd.conf | sed -e "s#htvcenter_WEBSERVER_DOCUMENT_ROOT#$htvcenter_WEBSERVER_DOCUMENT_ROOT#g" > /etc/httpd/conf.d/htvcenter-cloud.conf
	elif [ -f /etc/SuSE-release ]; then
		# for suse we link the htpasswd2 to htpasswd
		HTPASSWD=`htpasswd2`
		ln -s $HTPASSWD /usr/bin/htpasswd
		ln -sf $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/cloud/cloud-fortis/web/ $htvcenter_WEBSERVER_DOCUMENT_ROOT/cloud-fortis
		cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/cloud/etc/httpd/htvcenter-httpd.conf | sed -e "s#htvcenter_WEBSERVER_DOCUMENT_ROOT#$htvcenter_WEBSERVER_DOCUMENT_ROOT#g" > /etc/apache2/conf.d/htvcenter-cloud.conf
		# we should already have a special treatment for suse to allow followsymlinks in the default-setup
	fi
	$htvcenter_WEBSERVER_INIT reload
	# create the .htaccess file
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/cloud/etc/httpd/htvcenter-htaccess.conf | sed -e "s#htvcenter_WEBSERVER_DOCUMENT_ROOT#$htvcenter_WEBSERVER_DOCUMENT_ROOT#g" > $htvcenter_WEBSERVER_DOCUMENT_ROOT/cloud-fortis/user/.htaccess
	# create the default admin user
	touch $htvcenter_WEBSERVER_DOCUMENT_ROOT/cloud-fortis/user/.htpasswd
	chmod 666 $htvcenter_WEBSERVER_DOCUMENT_ROOT/cloud-fortis/user/.htpasswd

	# creating the tables
	if ! wget -q $WGET_NO_CERT_CHECK -O /dev/null --http-user=$USERNAME --http-password=$PASSWORD "$htvcenter_WEB_PROTOCOL://$resource_htvcenterserver/htvcenter/base/plugins/cloud/cloud-action.php?cloud_command=init"; then
		cloud_manager_log init "ERROR: Could not create the cloud-plugin tables in the database!"
		exit 1
	fi

	# create the directory for the cloud network-config of the appliances
	mkdir -p $htvcenter_SERVER_BASE_DIR/htvcenter/web/action/cloud-conf/
	chmod 777 $htvcenter_SERVER_BASE_DIR/htvcenter/web/action/cloud-conf/

	# create the directory for the custom user icons
	mkdir -p $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/cloud/cloud-fortis/web/user/custom-icons
	chmod 777 $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/cloud/cloud-fortis/web/user/custom-icons
	
}







USER=$2
PASS=$3

case "$1" in
	start)
		htvcenter_plugin_cloud_start
		;;
	stop)
		htvcenter_plugin_cloud_stop
		;;
	restart)
		htvcenter_plugin_cloud_stop
		sleep 1
		htvcenter_plugin_cloud_start
		;;
	init)
		htvcenter_plugin_cloud_init $USER $PASS
		;;
	uninstall)
		htvcenter_plugin_cloud_uninstall $USER $PASS
		;;
	*)
		echo "Usage: $0 {start|stop|restart|init|uninstall}"
		exit 1

esac
exit $?




