#!/bin/bash
# this is the boot-service init script for the Kvm-server hosts
#
# htvcenter Enterprise developed by htvcenter Enterprise GmbH.
#
# All source code and content (c) Copyright 2014, htvcenter Enterprise GmbH unless specifically noted otherwise.
#
# This source code is released under the htvcenter Enterprise Server and Client License, unless otherwise agreed with htvcenter Enterprise GmbH.
# The latest version of this license can be found here: http://htvcenter-enterprise.com/license
#
# By using this software, you acknowledge having read this license and agree to be bound thereby.
#
#           http://htvcenter-enterprise.com
#
# Copyright 2014, htvcenter Enterprise GmbH <info@htvcenter-enterprise.com>
#

export htvcenter_SERVER_BASE_DIR=@@htvcenter_SERVER_BASE_DIR@@
export OPENVSWITCH=@@htvcenter_PLUGIN_KVM_BRIDGE@@
export APP_NIC=@@htvcenter_APP_NIC@@
export PATH=/usr/sbin:/usr/bin:/sbin:/bin

export htvcenter_SOURCE_DIR="$htvcenter_SERVER_BASE_DIR/htvcenter/"
. $htvcenter_SERVER_BASE_DIR/htvcenter/include/htvcenter-functions
. $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/include/htvcenter-plugin-kvm-functions
. $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/htvcenter-plugin-kvm.conf
if [ -f $htvcenter_RESOURCE_PARAMETER_FILE ]; then
	. $htvcenter_RESOURCE_PARAMETER_FILE
elif [ -f $htvcenter_SERVER_BASE_DIR/htvcenter/etc/htvcenter-server.conf ]; then
	. $htvcenter_SERVER_BASE_DIR/htvcenter/etc/htvcenter-server.conf
	. $htvcenter_SERVER_BASE_DIR/htvcenter/include/htvcenter-server-functions
	resource_id=0
	htvcenter_server_get_config
	resource_htvcenterserver=$htvcenter_SERVER_IP_ADDRESS
	htvcenter_web_protocol=$htvcenter_WEB_PROTOCOL
fi
# define wget to use with https
if [ "$htvcenter_web_protocol" == "https" ]; then
	WGET="wget -q --no-check-certificate"
else
	WGET="wget -q"
fi

# find out the name
VM_BASE_DIR=$(pushd $(dirname $0) > /dev/null; echo $PWD; popd > /dev/null)
VM_NAME=`basename $VM_BASE_DIR`
# get the net config of the vm
. $VM_BASE_DIR/net1

# get vms resource parameters
if ! $WGET -q -t 1 -T 4 -O $VM_BASE_DIR/htvcenter-resource.conf "$htvcenter_web_protocol://${resource_htvcenterserver}/htvcenter/action/resource-monitor.php?resource_command=get_parameter&resource_mac=$KVM_VM_MAC_1"; then
	echo "ERROR: Could not refresh VMs resource-parameters!" | logger
else
	. $VM_BASE_DIR/htvcenter-resource.conf
fi
# get ip config
eval $appliance_capabilities
if [ "$IPT" != "" ]; then
	IP_TOKEN=`echo $IPT | cut -d'=' -f1`
	echo "- getting network configuration for token $IP_TOKEN nic $APP_NIC" | logger
	if ! $WGET -O $VM_BASE_DIR/htvcenter-network.$APP_NIC.conf "$htvcenter_web_protocol://${resource_htvcenterserver}/htvcenter/boot-service/ip-mgmt-appliance-config.php?ip_mgmt_command=get_config&appliance_id=$appliance_id&ip_mgmt_nic_id=$APP_NIC&ip_mgmt_token=$IP_TOKEN"; then
		echo "ERROR: Could not get ip-configuration from htvcenter-server at ${resource_htvcenterserver}!"
		exit -1
	fi
	. $VM_BASE_DIR/htvcenter-network.$APP_NIC.conf
else
	echo "NOTICE: No ip-configuration for VM available. Continuing..." | logger
fi

# now attach the tap device to the bridge
ifconfig $1 0.0.0.0 up
if [ "$VLAN_ID" != "" ]; then
	VLAN_TAG_PARAMETER="tag=$VLAN_ID"
fi
# make sure it is not setup already
ovs-vsctl del-port ${OPENVSWITCH} $1
# attach tap
ovs-vsctl add-port ${OPENVSWITCH} $1 $VLAN_TAG_PARAMETER

