#!/bin/bash
# this is the boot-service init script for the Kvm-server hosts
#
# htvcenter Enterprise developed by htvcenter Enterprise GmbH.
#
# All source code and content (c) Copyright 2014, htvcenter Enterprise GmbH unless specifically noted otherwise.
#
# This source code is released under the htvcenter Enterprise Server and Client License, unless otherwise agreed with htvcenter Enterprise GmbH.
# The latest version of this license can be found here: http://htvcenter-enterprise.com/license
#
# By using this software, you acknowledge having read this license and agree to be bound thereby.
#
#           http://htvcenter-enterprise.com
#
# Copyright 2014, htvcenter Enterprise GmbH <info@htvcenter-enterprise.com>
#

export htvcenter_SERVER_BASE_DIR=@@htvcenter_SERVER_BASE_DIR@@
export OPENVSWITCH=@@htvcenter_PLUGIN_KVM_BRIDGE@@
export PATH=/usr/sbin:/usr/bin:/sbin:/bin

# remove the tap dev
ifconfig $1 0.0.0.0 down
ovs-vsctl del-port ${OPENVSWITCH} $1

