#!/bin/bash
# this is the functions file for the vmware-vsphere-plugin
#
# HyperTask Enterprise developed by HyperTask Enterprise GmbH.
#
# All source code and content (c) Copyright 2014, HyperTask Enterprise GmbH unless specifically noted otherwise.
#
# This source code is released under the HyperTask Enterprise Server and Client License, unless otherwise agreed with HyperTask Enterprise GmbH.
# The latest version of this license can be found here: http://htvcenter-enterprise.com/license
#
# By using this software, you acknowledge having read this license and agree to be bound thereby.
#
#           http://htvcenter-enterprise.com
#
# Copyright 2014, HyperTask Enterprise GmbH <info@htvcenter-enterprise.com>
#

VM_ACTION_POWERON="poweron"
VM_ACTION_POWEROFF="poweroff"
VM_ACTION_SUSPEND="suspend"
VM_ACTION_RESET="reset"
VM_ACTION_REBOOT="reboot"
VM_ACTION_SHUTDOWN="shutdown"
VM_ACTION_STANDBY="standby"

################ common vmware-vsphere functions

# logs for vmware-vsphere
function vmware_vsphere_log() {
	local COMPONENT=$1
	shift
	local MESSAGE=$@
	echo "vmware-vsphere plug-in" "$COMPONENT : $MESSAGE"
	logger -i -t "vmware-vsphere plug-in" "$COMPONENT : $MESSAGE"
}


# deps function
function check_vmware_vsphere_deps() {

	# check and fullfill dependencies
	# screen
	if ! htvcenter_full_fill_os_dependency screen screen; then
		return 1
	fi
	if [ -x /usr/bin/screen.real ]; then
		export RUNSCREEN="/usr/bin/screen.real"
	else
		export RUNSCREEN=`which screen`
	fi
	# wget
	if ! htvcenter_full_fill_os_dependency wget wget; then
		return 1
	fi
	return 0
}



################ vmware-vsphere functions






