#!/bin/bash
# init script for the htvcenter template-plugin
#
# htvcenter Enterprise developed by htvcenter Enterprise GmbH.
#
# All source code and content (c) Copyright 2014, htvcenter Enterprise GmbH unless specifically noted otherwise.
#
# This source code is released under the htvcenter Enterprise Server and Client License, unless otherwise agreed with htvcenter Enterprise GmbH.
# The latest version of this license can be found here: http://htvcenter-enterprise.com/license
#
# By using this software, you acknowledge having read this license and agree to be bound thereby.
#
#           http://htvcenter-enterprise.com
#
# Copyright 2014, htvcenter Enterprise GmbH <info@htvcenter-enterprise.com>
#

htvcenter_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
. $htvcenter_SERVER_BASE_DIR/htvcenter/etc/htvcenter-server.conf
. $htvcenter_SERVER_BASE_DIR/htvcenter/include/htvcenter-functions
. $htvcenter_SERVER_BASE_DIR/htvcenter/include/htvcenter-server-functions
. $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/template/include/htvcenter-plugin-template-functions
. $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/template/etc/htvcenter-plugin-template.conf
htvcenter_server_get_config
export LANG=C
# define wget to use with https
if [ "$htvcenter_WEB_PROTOCOL" == "https" ]; then
	WGET_NO_CERT_CHECK="--no-check-certificate"
fi


function htvcenter_plugin_template_start() {
	echo "Starting the htvcenter template-plugin"

	# TODO: add your commands here for the Plugin start

	touch $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/base/plugins/template/.running
}


function htvcenter_plugin_template_stop() {
	echo "Stopping the htvcenter template-plugin"

	# TODO: add your commands here for the Plugin stop

	rm -f $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/base/plugins/template/.running
}

function htvcenter_plugin_template_uninstall() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "template: Please give a username to uninstall the plugin : "
		read USERNAME
		echo
		echo -n "template: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Uninstalling the htvcenter template-plugin"
	htvcenter_plugin_template_stop

	# removing the template tables
	if ! wget -q $WGET_NO_CERT_CHECK -O /dev/null --http-user=$USERNAME --http-password=$PASSWORD "$htvcenter_WEB_PROTOCOL://localhost/htvcenter/base/plugins/template/template-action.php?template_command=uninstall"; then
		template_manager_log uninstall "ERROR: Could not drop the template-plugin tables in the database!"
		exit 1
	fi

	# TODO: add your commands here for the Plugin disable (uninstall)

	rm -f $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/boot-service/boot-service-template.tgz
	rm -f $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/base/plugins/template
}

function htvcenter_plugin_template_init() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "template: Please give a username to init the plugin : "
		read USERNAME
		echo
		echo -n "template: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi

	echo "Initializing the htvcenter template-plugin"
	# linking the web dir
	ln -sf $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/template/web $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/base/plugins/template
	# link the boot-service
	ln -sf $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/template/web/boot-service-template.tgz $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/boot-service/boot-service-template.tgz

	# creating the tables
	if ! wget -q $WGET_NO_CERT_CHECK -O /dev/null --http-user=$USERNAME --http-password=$PASSWORD "$htvcenter_WEB_PROTOCOL://localhost/htvcenter/base/plugins/template/template-action.php?template_command=init&template_domain=$htvcenter_SERVER_DOMAIN"; then
		template_manager_log init "ERROR: Could not create the template-plugin tables in the database!"
		exit 1
	fi

	# TODO: add your commands here for the Plugin enable (init)


}







USER=$2
PASS=$3

case "$1" in
	start)
		htvcenter_plugin_template_start
		;;
	stop)
		htvcenter_plugin_template_stop
		;;
	restart)
		htvcenter_plugin_template_stop
		sleep 1
		htvcenter_plugin_template_start
		;;
	init)
		htvcenter_plugin_template_init $USER $PASS
		;;
	uninstall)
		htvcenter_plugin_template_uninstall $USER $PASS
		;;
	*)
		echo "Usage: $0 {start|stop|restart|init|uninstall}"
		exit 1

esac
exit $?




