#!/bin/bash
# this is the boot-service init script for the template resources
#
# htvcenter Enterprise developed by htvcenter Enterprise GmbH.
#
# All source code and content (c) Copyright 2014, htvcenter Enterprise GmbH unless specifically noted otherwise.
#
# This source code is released under the htvcenter Enterprise Server and Client License, unless otherwise agreed with htvcenter Enterprise GmbH.
# The latest version of this license can be found here: http://htvcenter-enterprise.com/license
#
# By using this software, you acknowledge having read this license and agree to be bound thereby.
#
#           http://htvcenter-enterprise.com
#
# Copyright 2014, htvcenter Enterprise GmbH <info@htvcenter-enterprise.com>
#

htvcenter_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
# for including the package functions
export htvcenter_SOURCE_DIR="$htvcenter_SERVER_BASE_DIR/htvcenter/"
. $htvcenter_SERVER_BASE_DIR/htvcenter/include/htvcenter-functions
. $htvcenter_SERVER_BASE_DIR/htvcenter/include/htvcenter-package-functions
. $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/template/include/htvcenter-plugin-template-functions
. $htvcenter_RESOURCE_PARAMETER_FILE
htvcenter_SERVER_IP=$resource_htvcenterserver

# do not run on idle resources
if [ "$resource_image" == "idle" ]; then
	exit 0
fi

# also do not run before the real init of the rootfs
# if we have this file /etc/initrd-devices.conf we are still in the initrd
if [ -f /etc/initrd-devices.conf ]; then

	# TODO: add your commands to run in the initrd-stage on a managed system (network-deployment only)

	exit 0
fi


function template_start() {
	echo "Starting the htvcenter template-plugin"
	template_stop 1>/dev/null 2>&1

	# TODO: add your commands to in the init phase on a managed system

}


function template_stop() {
	echo "Stopping the htvcenter template-plugin"

	# TODO: add your commands to in the init phase on a managed system

}





case "$1" in
	start)
		template_start
		;;
	stop)
		template_stop
		;;
	restart)
		template_stop
		sleep 1
		template_start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1

esac
exit $?













