#!/bin/bash
#
# htvcenter Enterprise developed by htvcenter Enterprise GmbH.
#
# All source code and content (c) Copyright 2012, htvcenter Enterprise GmbH unless specifically noted otherwise.
#
# This source code is released under the htvcenter Enterprise Server and Client License, unless otherwise agreed with htvcenter Enterprise GmbH.
# The latest version of this license can be found here: http://htvcenter-enterprise.com/license
#
# By using this software, you acknowledge having read this license and agree to be bound thereby.
#
#           http://htvcenter-enterprise.com
#
# Copyright 2012, htvcenter Enterprise GmbH <info@htvcenter-enterprise.com>
#

VM_XEN_CONFIG=/var/run/xen-vm-config.conf

while [ ! -f "$VM_XEN_CONFIG" ]; do
	sleep 1
done
. $VM_XEN_CONFIG


TAP_DEV_NUMBER=`echo $1 | sed -e "s/tap//g"`
CURRENT_TAP=$(( $TAP_DEV_NUMBER - $HOST_TAP_DEVICES ))

case "$CURRENT_TAP" in
	0)
		if [ "$VM_TAP_0" != "" ]; then
			VLAN_TAG_PARAMETER="tag=$VM_TAP_0"
		fi
		;;
	1)
		if [ "$VM_TAP_1" != "" ]; then
			VLAN_TAG_PARAMETER="tag=$VM_TAP_1"
		fi
                ;;
        2)
		if [ "$VM_TAP_2" != "" ]; then
                	VLAN_TAG_PARAMETER="tag=$VM_TAP_2"
		fi
                ;;
        3)
		if [ "$VM_TAP_3" != "" ]; then
                	VLAN_TAG_PARAMETER="tag=$VM_TAP_3"
		fi
                ;;
        4)
		if [ "$VM_TAP_4" != "" ]; then
                	VLAN_TAG_PARAMETER="tag=$VM_TAP_4"
		fi
                ;;
esac


if [ "$VM_STATUS" == "idle" ]; then
	VLAN_TAG_PARAMETER=""
fi

echo "!!!!!!!!!!!!! qemu-ifup with vm-status $VM_STATUS - $VLAN_TAG_PARAMETER" | logger

ifconfig $1 0.0.0.0 up
/usr/local/bin/ovs-vsctl del-port $2 $1
/usr/local/bin/ovs-vsctl add-port $2 $1 $VLAN_TAG_PARAMETER
ip link set "$2" up

# check how many taps we have now on the host
# if we reached host-taps + vm-nics then it is the last nic to prepare
# and time to remove the /var/run/xen-vm-config.conf
CURRENT_HOST_TAP_DEVICES=`ifconfig | grep ^tap | wc -l`
LAST_HOST_TAP_DEV=$(( $HOST_TAP_DEVICES + $VM_NICS ))
if [ "$CURRENT_HOST_TAP_DEVICES" == "$LAST_HOST_TAP_DEV" ]; then
	echo "!!!!!!!!!!!!!!!!!!!!!!!!!!! removing the $VM_XEN_CONFIG" | logger
	rm -f $VM_XEN_CONFIG
else
	echo "!!!!!!!!!!------ $HOST_TAP_DEVICES + $VM_NICS" | logger
fi








