#!/bin/bash
# this is the boot-service init script for the novnc resources
#
# htvcenter Enterprise developed by htvcenter Enterprise GmbH.
#
# All source code and content (c) Copyright 2014, htvcenter Enterprise GmbH unless specifically noted otherwise.
#
# This source code is released under the htvcenter Enterprise Server and Client License, unless otherwise agreed with htvcenter Enterprise GmbH.
# The latest version of this license can be found here: http://htvcenter-enterprise.com/license
#
# By using this software, you acknowledge having read this license and agree to be bound thereby.
#
#           http://htvcenter-enterprise.com
#
# Copyright 2014, htvcenter Enterprise GmbH <info@htvcenter-enterprise.com>
#

htvcenter_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
# for including the package functions
export htvcenter_SOURCE_DIR="$htvcenter_SERVER_BASE_DIR/htvcenter/"
. $htvcenter_SERVER_BASE_DIR/htvcenter/include/htvcenter-functions
. $htvcenter_SERVER_BASE_DIR/htvcenter/include/htvcenter-package-functions
. $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/novnc/include/htvcenter-plugin-novnc-functions
. $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/novnc/etc/htvcenter-plugin-novnc.conf
. $htvcenter_RESOURCE_PARAMETER_FILE
# define wget to use with https
if [ "$htvcenter_web_protocol" == "https" ]; then
	WGET_NO_CERT_CHECK="--no-check-certificate"
fi

# do not run on idle resources
if [ "$resource_image" == "idle" ]; then
	exit 0
fi
# also do not run before the real init of the rootfs
# if we have this file /etc/initrd-devices.conf we are still in the initrd
if [ -f /etc/initrd-devices.conf ]; then
	exit 0
fi


function novnc_start() {
	echo "Starting the htvcenter novnc-plugin"
	novnc_stop 1>/dev/null 2>&1
	return 0
}


function novnc_stop() {
	echo "Stopping the htvcenter novnc-plugin"
	return 0
}



case "$1" in
	start)
		novnc_start
		;;
	stop)
		novnc_stop
		;;
	restart)
		novnc_stop
		sleep 1
		novnc_start
		;;
	*)
		echo "Usage: $0 {start|stop|restart|createcert}"
		exit 1

esac
exit $?













