#!/bin/bash
# this script automatically monitors kvm vms
#
# htvcenter Enterprise developed by htvcenter Enterprise GmbH.
#
# All source code and content (c) Copyright 2014, htvcenter Enterprise GmbH unless specifically noted otherwise.
#
# This source code is released under the htvcenter Enterprise Server and Client License, unless otherwise agreed with htvcenter Enterprise GmbH.
# The latest version of this license can be found here: http://htvcenter-enterprise.com/license
#
# By using this software, you acknowledge having read this license and agree to be bound thereby.
#
#           http://htvcenter-enterprise.com
#
# Copyright 2014, htvcenter Enterprise GmbH <info@htvcenter-enterprise.com>
#
# this script automatically monitors opsi auto-installations
htvcenter_SERVER_BASE_DIR=$(dirname $0)/../../../..
htvcenter_SERVER_BASE_DIR=$(pushd $htvcenter_SERVER_BASE_DIR > /dev/null && echo $PWD && popd > /dev/null)
. $htvcenter_SERVER_BASE_DIR/htvcenter/include/htvcenter-functions
. $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/opsi/include/htvcenter-plugin-opsi-functions
htvcenter_POSTENCODE="$htvcenter_SERVER_BASE_DIR/htvcenter/sbin/htvcenter-postencode"
if [ -f $htvcenter_RESOURCE_PARAMETER_FILE ]; then
	. $htvcenter_RESOURCE_PARAMETER_FILE
	htvcenter_SERVER_IP=$resource_htvcenterserver
	export SERVER_PROTOCOL=$htvcenter_web_protocol
else
	echo "ERROR: This script runs on an integrated Opsi-Server only!"
	exit 6
fi
export LANG=C
htvcenter_EVENT="statistics"
htvcenter_ACTIVE_STATE="transition"
htvcenter_STARTING_STATE="starting"
htvcenter_CLIENT_OPSI_INSTALL_DIR="/opt/pcbin/install/htvcenter-client"

# define wget to use with https
if [ "$SERVER_PROTOCOL" == "https" ]; then
	WGET_NO_CERT_CHECK="--no-check-certificate --random-file=/dev/random"
fi

# let only root run this script
WHOAMI=`whoami`
if [ "$WHOAMI" != "root" ]; then
	echo "ERROR: Please run this script as root!"
	exit 6
fi

# mac is the identifier
RESOURCE_ID=$1
RESOURCE_NAME=$2
RESOURCE_DOMAIN=$3
if [ "$RESOURCE_ID" == "" ] || [ "$RESOURCE_NAME" == "" ]  || [ "$RESOURCE_DOMAIN" == "" ]; then
	echo "Usage: $0 <resource_id> <resource_name> <resource_domain> "
	exit 1
fi


# local used functions
function send_info() {
	current_state=`urlencodestring $htvcenter_ACTIVE_STATE`
	current_event=`urlencodestring $htvcenter_EVENT`
	MESSAGEDATA="resource_id=$RESOURCE_ID&resource_uptime=$current_uptime&resource_state=$current_state&resource_event=$current_event";
	htvcenter_RESOURCE_INFO_URL="$SERVER_PROTOCOL://$resource_htvcenterserver/htvcenter/action/resource-monitor.php?resource_command=update_info&$MESSAGEDATA"
	wget $WGET_NO_CERT_CHECK -q -O /dev/null "$htvcenter_RESOURCE_INFO_URL"
}



# uptime
function find_uptime() {
	if [ -f /proc/uptime ]; then
		current_uptime=`cat /proc/uptime | cut -d'.' -f 1`
	fi
	if [ -z "$current_uptime" ]; then
		current_uptime=0
	fi
}


# main loop
while (true); do
	# get install state
	opsi-admin -d method getInstalledProductIds_list $RESOURCE_NAME.$RESOURCE_DOMAIN > /tmp/$RESOURCE_NAME.$RESOURCE_DOMAIN.install.log
	if grep htvcenter-client /tmp/$RESOURCE_NAME.$RESOURCE_DOMAIN.install.log; then
			# ready installed, exit the montird, remove the install-info file
			# rm -f $htvcenter_CLIENT_OPSI_INSTALL_DIR/$RESOURCE_NAME.htvcenter-client.conf
			exit 0
	fi
	# uptime
	find_uptime
	# sending statistics
	send_info
	# delay
	sleep $resource_senddelay
done
# never reached
exit 0

















