#!/bin/bash
# this is the functions file for the hyperv-plugin
#
# htvcenter Enterprise developed by htvcenter Enterprise GmbH.
#
# All source code and content (c) Copyright 2014, htvcenter Enterprise GmbH unless specifically noted otherwise.
#
# This source code is released under the htvcenter Enterprise Server and Client License, unless otherwise agreed with htvcenter Enterprise GmbH.
# The latest version of this license can be found here: http://htvcenter-enterprise.com/license
#
# By using this software, you acknowledge having read this license and agree to be bound thereby.
#
#           http://htvcenter-enterprise.com
#
# Copyright 2014, htvcenter Enterprise GmbH <info@htvcenter-enterprise.com>
#

WINEXE="$htvcenter_SERVER_BASE_DIR/htvcenter/plugins/hyperv/bin/winexe/winexe"

################ common hyperv functions

# logs for hyperv
function hyperv_log() {
	local COMPONENT=$1
	shift
	local MESSAGE=$@
	echo "hyperv plug-in" "$COMPONENT : $MESSAGE"
	logger -i -t "hyperv plug-in" "$COMPONENT : $MESSAGE"
}


# deps function
function check_hyperv_deps() {

	# check and fullfill dependencies
	# screen
	if ! htvcenter_full_fill_os_dependency screen screen; then
		return 1
	fi
	if [ -x /usr/bin/screen.real ]; then
		export RUNSCREEN="/usr/bin/screen.real"
	else
		export RUNSCREEN=`which screen`
	fi
	# wget
	if ! htvcenter_full_fill_os_dependency wget wget; then
		return 1
	fi
	return 0
}



################ hyperv functions


function check_hyperv_online() {
	HYPER_V_IP=$1
	if $WINEXE -U $HYPER_V_IP/Administrator% //$HYPER_V_IP "powershell.exe -inputformat none -ExecutionPolicy RemoteSigned Get-VM" | grep -w NT_STATUS_LOGON_FAILURE 2>/dev/null 1>&2; then
		return 0
	else
		return 1
	fi
}



