#!/bin/bash
#
# htvcenter Enterprise developed by htvcenter Enterprise GmbH.
#
# All source code and content (c) Copyright 2014, htvcenter Enterprise GmbH unless specifically noted otherwise.
#
# This source code is released under the htvcenter Enterprise Server and Client License, unless otherwise agreed with htvcenter Enterprise GmbH.
# The latest version of this license can be found here: http://htvcenter-enterprise.com/license
#
# By using this software, you acknowledge having read this license and agree to be bound thereby.
#
#           http://htvcenter-enterprise.com
#
# Copyright 2014, htvcenter Enterprise GmbH <info@htvcenter-enterprise.com>

htvcenter_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
. $htvcenter_SERVER_BASE_DIR/htvcenter/etc/htvcenter-server.conf
. $htvcenter_SERVER_BASE_DIR/htvcenter/include/htvcenter-functions
. $htvcenter_SERVER_BASE_DIR/htvcenter/include/htvcenter-server-functions
. $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/fai/include/htvcenter-plugin-fai-functions
. $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/fai/etc/htvcenter-plugin-fai.conf
# get the ip config
htvcenter_server_get_config
export resource_htvcenterserver=$htvcenter_SERVER_IP_ADDRESS
export LANG=C
# define wget to use with https
if [ "$htvcenter_WEB_PROTOCOL" == "https" ]; then
	WGET_NO_CERT_CHECK="--no-check-certificate"
fi

function htvcenter_plugin_fai_start() {
	echo "Starting the htvcenter fai-plugin"
	touch $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/base/plugins/fai/.running
}


function htvcenter_plugin_fai_stop() {
	echo "Stopping the htvcenter fai-plugin"
	rm -f $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/base/plugins/fai/.running
}

function htvcenter_plugin_fai_uninstall() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "fai: Please give a username to uninstall the plugin : "
		read USERNAME
		echo
		echo -n "fai: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Uninstalling the htvcenter fai-plugin"
	htvcenter_plugin_fai_stop
	htvcenter_server_remove_deployment_type $USERNAME $PASSWORD fai-deployment
	# removing the table
	if ! wget -q $WGET_NO_CERT_CHECK -O /dev/null --http-user=$USERNAME --http-password=$PASSWORD "$htvcenter_WEB_PROTOCOL://$resource_htvcenterserver/htvcenter/base/plugins/fai/fai-action.php?fai_command=uninstall"; then
		fai_log init "ERROR: Could not drop the fai-plugin tables in the database!"
		return 1
	fi
	rm -f $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/base/plugins/fai
	rm -f $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/boot-service/boot-service-fai.tgz
	rm -f $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/boot-service/image.fai-deployment.php
	rm -f $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/boot-service/template.fai-deployment.php

}

function htvcenter_plugin_fai_init() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "fai: Please give a username to init the plugin : "
		read USERNAME
		echo
		echo -n "fai: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Initializing the htvcenter fai-plugin"
	htvcenter_server_add_deployment_type $USERNAME $PASSWORD fai-deployment fai-deployment "Automatic Linux Installation (Fai)" fai "Physical local disk (Fai)"
	# linking the web dir
	ln -sf $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/fai/web $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/base/plugins/fai
	# creating the table
	if ! wget -q $WGET_NO_CERT_CHECK -O /dev/null --http-user=$USERNAME --http-password=$PASSWORD "$htvcenter_WEB_PROTOCOL://$resource_htvcenterserver/htvcenter/base/plugins/fai/fai-action.php?fai_command=init"; then
		fai_log init "ERROR: Could not create the fai-plugin tables in the database!"
		rm -f $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/base/plugins/fai
		return 1
	fi
	# link the boot-service
	ln -sf $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/fai/web/boot-service-fai.tgz $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/boot-service/boot-service-fai.tgz
	# link the image + template hooks
	ln -sf $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/fai/web/image.fai-deployment.php $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/boot-service/image.fai-deployment.php
	ln -sf $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/fai/web/template.fai-deployment.php $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/boot-service/template.fai-deployment.php
	# place for the storage stat files
	mkdir -p $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/fai/web/storage
	chmod -R 777 $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/fai/web/storage
	echo "Order deny,allow" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/fai/web/storage/.htaccess
	echo "Deny from all" >> $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/fai/web/storage/.htaccess
	# creating place for autoinstall files
	ln -sf $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/fai/bin/htvcenter-fai-autoinstall-client $htvcenter_SERVER_BASE_DIR/htvcenter/web/boot-service/htvcenter-fai-autoinstall-client
	ln -sf $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/fai/etc/templates/htvcenter_client_fai_auto_install.snippets $htvcenter_SERVER_BASE_DIR/htvcenter/web/boot-service/htvcenter_client_fai_auto_install.snippets

}

USER=$2
PASS=$3

case "$1" in
	start)
		htvcenter_plugin_fai_start
		;;
	stop)
		htvcenter_plugin_fai_stop
		;;
	restart)
		htvcenter_plugin_fai_stop
		sleep 1
		htvcenter_plugin_fai_start
		;;
	init)
		htvcenter_plugin_fai_init $USER $PASS
		;;
	uninstall)
		htvcenter_plugin_fai_uninstall $USER $PASS
		;;
	*)
		echo "Usage: $0 {start|stop|restart|init|uninstall}"
		exit 1

esac
exit $?




