#!/bin/bash
# init script for the htvcenter development-plugin
#
# htvcenter Enterprise developed by htvcenter Enterprise GmbH.
#
# All source code and content (c) Copyright 2014, htvcenter Enterprise GmbH unless specifically noted otherwise.
#
# This source code is released under the htvcenter Enterprise Server and Client License, unless otherwise agreed with htvcenter Enterprise GmbH.
# The latest version of this license can be found here: http://htvcenter-enterprise.com/license
#
# By using this software, you acknowledge having read this license and agree to be bound thereby.
#
#           http://htvcenter-enterprise.com
#
# Copyright 2014, htvcenter Enterprise GmbH <info@htvcenter-enterprise.com>
#

htvcenter_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
. $htvcenter_SERVER_BASE_DIR/htvcenter/etc/htvcenter-server.conf
. $htvcenter_SERVER_BASE_DIR/htvcenter/include/htvcenter-functions
. $htvcenter_SERVER_BASE_DIR/htvcenter/include/htvcenter-server-functions
. $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/development/include/htvcenter-plugin-development-functions
. $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/development/etc/htvcenter-plugin-development.conf
htvcenter_server_get_config
export LANG=C
# define wget to use with https
if [ "$htvcenter_WEB_PROTOCOL" == "https" ]; then
	WGET_NO_CERT_CHECK="--no-check-certificate"
fi


function htvcenter_plugin_development_start() {
	echo "Starting the htvcenter development-plugin"
	touch $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/base/plugins/development/.running
}


function htvcenter_plugin_development_stop() {
	echo "Stopping the htvcenter development-plugin"
	rm -f $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/base/plugins/development/.running
}

function htvcenter_plugin_development_uninstall() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "development: Please give a username to uninstall the plugin : "
		read USERNAME
		echo
		echo -n "development: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Uninstalling the htvcenter development-plugin"
	htvcenter_plugin_development_stop
	rm -f $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/base/plugins/development
}

function htvcenter_plugin_development_init() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "development: Please give a username to init the plugin : "
		read USERNAME
		echo
		echo -n "development: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi

	echo "Initializing the htvcenter development-plugin"
	# linking the web dir
	ln -sf $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/development/web $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/base/plugins/development

}







USER=$2
PASS=$3

case "$1" in
	start)
		htvcenter_plugin_development_start
		;;
	stop)
		htvcenter_plugin_development_stop
		;;
	restart)
		htvcenter_plugin_development_stop
		sleep 1
		htvcenter_plugin_development_start
		;;
	init)
		htvcenter_plugin_development_init $USER $PASS
		;;
	uninstall)
		htvcenter_plugin_development_uninstall $USER $PASS
		;;
	*)
		echo "Usage: $0 {start|stop|restart|init|uninstall}"
		exit 1

esac
exit $?




