#!/bin/bash
# this is the functions file for the chatbot-plugin
#
# htvcenter Enterprise developed by htvcenter Enterprise GmbH.
#
# All source code and content (c) Copyright 2014, htvcenter Enterprise GmbH unless specifically noted otherwise.
#
# This source code is released under the htvcenter Enterprise Server and Client License, unless otherwise agreed with htvcenter Enterprise GmbH.
# The latest version of this license can be found here: http://htvcenter-enterprise.com/license
#
# By using this software, you acknowledge having read this license and agree to be bound thereby.
#
#           http://htvcenter-enterprise.com
#
# Copyright 2014, htvcenter Enterprise GmbH <info@htvcenter-enterprise.com>
#

################ common multi-cloud functions

# logs for multi-cloud
function miltu_cloud_manager_log() {
	local COMPONENT=$1
	shift
	local MESSAGE=$@
	logger -i -t "multi_cloud plug-in" "$COMPONENT : $MESSAGE"
}





