#!/bin/bash
# init script for the htvcenter lcmc plugin
#
# htvcenter Enterprise developed by htvcenter Enterprise GmbH.
#
# All source code and content (c) Copyright 2014, htvcenter Enterprise GmbH unless specifically noted otherwise.
#
# This source code is released under the htvcenter Enterprise Server and Client License, unless otherwise agreed with htvcenter Enterprise GmbH.
# The latest version of this license can be found here: http://htvcenter-enterprise.com/license
#
# By using this software, you acknowledge having read this license and agree to be bound thereby.
#
#           http://htvcenter-enterprise.com
#
# Copyright 2014, htvcenter Enterprise GmbH <info@htvcenter-enterprise.com>
#
htvcenter_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
. $htvcenter_SERVER_BASE_DIR/htvcenter/etc/htvcenter-server.conf
. $htvcenter_SERVER_BASE_DIR/htvcenter/include/htvcenter-functions
. $htvcenter_SERVER_BASE_DIR/htvcenter/include/htvcenter-server-functions
. $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/lcmc/include/htvcenter-plugin-lcmc-functions
. $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/lcmc/etc/htvcenter-plugin-lcmc.conf

LCMC_MC_VERSION="1.3.2"

function htvcenter_plugin_lcmc_start() {
	echo "Starting the htvcenter lcmc-plugin"
	htvcenter_plugin_lcmc_stop 1>/dev/null 2>&1
	touch $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/base/plugins/lcmc/.running
	return $RET
}


function htvcenter_plugin_lcmc_stop() {
	echo "Stopping the htvcenter lcmc-plugin"
	rm -f $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/base/plugins/lcmc/.running
	return 0
}


function htvcenter_plugin_lcmc_init() {
	echo "Initializing the htvcenter lcmc-plugin"
	# copy lcmc-applet to the cloud
	mkdir -p $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/cloud/cloud-fortis/web/user/lcmc/
	cd $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/cloud/cloud-fortis/web/user/lcmc/
	ln -sf $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/lcmc/web/lcmc-gui.php .
	ln -sf $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/lcmc/web/LCMC-applet-"$LCMC_MC_VERSION".jar .
	cd - 1>/dev/null
	cp -f $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/lcmc/web/img/plugin.png $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/cloud/cloud-fortis/web/img/ha_console.png
	# linking the web dir
	ln -sf $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/lcmc/web $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/base/plugins/lcmc
	return 0
}


function htvcenter_plugin_lcmc_uninstall() {
	echo "Uninstalling the htvcenter lcmc-plugin"
	htvcenter_plugin_lcmc_stop
	# remove from cloud
	rm -rf $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/cloud/cloud-fortis/web/user/lcmc
	rm -f $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/cloud/cloud-fortis/web/img/ha_console.png
	# unlinking the web dir
	rm -f $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/base/plugins/lcmc
}



case "$1" in
	start)
		htvcenter_plugin_lcmc_start
		;;
	stop)
		htvcenter_plugin_lcmc_stop
		;;
	restart)
		htvcenter_plugin_lcmc_stop
		sleep 1
		htvcenter_plugin_lcmc_start
		;;
	init)
		htvcenter_plugin_lcmc_init
		;;
	uninstall)
		htvcenter_plugin_lcmc_uninstall
		;;
	*)
		echo "Usage: $0 {start|stop|restart|init|uninstall}"
		exit 1

esac
exit $?


