#!/bin/bash
# this is the functions file for the xen-plugin
#
# htvcenter Enterprise developed by htvcenter Enterprise GmbH.
#
# All source code and content (c) Copyright 2012, htvcenter Enterprise GmbH unless specifically noted otherwise.
#
# This source code is released under the htvcenter Enterprise Server and Client License, unless otherwise agreed with htvcenter Enterprise GmbH.
# The latest version of this license can be found here: http://htvcenter-enterprise.com/license
#
# By using this software, you acknowledge having read this license and agree to be bound thereby.
#
#           http://htvcenter-enterprise.com
#
# Copyright 2012, htvcenter Enterprise GmbH <info@htvcenter-enterprise.com>
#


# some definitions
DEFAULT_IMAGE_SIZE=5000
LV_SIZE_DEFAULT=5000


################ common xen functions

# logs for xen
function xen_log() {
	local COMPONENT=$1
	shift
	local MESSAGE=$@
	logger -i -t "xen plug-in" "$COMPONENT : $MESSAGE"
}

################ xen functions


# deps function
function check_xen_deps() {

	# check and fullfill dependencies
	# screen
	if ! htvcenter_full_fill_os_dependency screen screen; then
		return 1
	fi
	if [ -x /usr/bin/screen.real ]; then
		export RUNSCREEN="/usr/bin/screen.real"
	else
		export RUNSCREEN=`which screen`
	fi
	# wget
	if ! htvcenter_full_fill_os_dependency wget wget; then
		return 1
	fi
	# procmail for lockfile
	if ! htvcenter_full_fill_os_dependency lockfile procmail; then
		return 1
	fi
	# resize2fs
	if ! htvcenter_full_fill_os_dependency resize2fs e2fsprogs; then
		return 1
	fi
	# kpartx
	if ! htvcenter_full_fill_os_dependency kpartx kpartx; then
		return 1
	fi
	# lvm2
	if ! htvcenter_full_fill_os_dependency lvs lvm2; then
		return 1
	fi
	# bridge-utils
	if ! htvcenter_full_fill_os_dependency brctl bridge-utils; then
		return 1
	fi

	# different package names for different distros
	if [ -f /etc/debian_version ]; then
		if ! htvcenter_full_fill_os_dependency vconfig vlan; then
			return 1
		fi
		if ! htvcenter_install_os_dependency ntfsprogs; then
			if ! htvcenter_full_fill_os_dependency ntfsresize ntfs-3g; then
				return 1
			fi
		fi
		# nfs-common
		if ! htvcenter_full_fill_os_dependency mount.nfs nfs-common; then
			return 1
		fi
	elif [ -f /etc/redhat-release ]; then
		if ! htvcenter_full_fill_os_dependency vconfig vconfig; then
			return 1
		fi
		if ! htvcenter_full_fill_os_dependency ntfsresize ntfsprogs; then
			return 1
		fi
		# nfs-utils
		if ! htvcenter_full_fill_os_dependency mount.nfs nfs-utils; then
			return 1
		fi

	elif [ -f /etc/SuSE-release ]; then
		if ! htvcenter_full_fill_os_dependency vconfig vlan; then
			return 1
		fi
		if ! htvcenter_full_fill_os_dependency ntfsresize ntfsprogs; then
			return 1
		fi
		# nfs-utils
		if ! htvcenter_full_fill_os_dependency mount.nfs nfs-client; then
			return 1
		fi
	fi


}



