#!/bin/bash
# this is the boot-service init script for the role-administration resources
#
# htvcenter Enterprise developed by htvcenter Enterprise GmbH.
#
# All source code and content (c) Copyright 2014, htvcenter Enterprise GmbH unless specifically noted otherwise.
#
# This source code is released under the htvcenter Enterprise Server and Client License, unless otherwise agreed with htvcenter Enterprise GmbH.
# The latest version of this license can be found here: http://htvcenter-enterprise.com/license
#
# By using this software, you acknowledge having read this license and agree to be bound thereby.
#
#           http://htvcenter-enterprise.com
#
# Copyright 2014, htvcenter Enterprise GmbH <info@htvcenter-enterprise.com>
#

htvcenter_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
# for including the package functions
export htvcenter_SOURCE_DIR="$htvcenter_SERVER_BASE_DIR/htvcenter/"
. $htvcenter_SERVER_BASE_DIR/htvcenter/include/htvcenter-functions
. $htvcenter_SERVER_BASE_DIR/htvcenter/include/htvcenter-package-functions
. $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/role-administration/include/htvcenter-plugin-role-administration-functions
. $htvcenter_RESOURCE_PARAMETER_FILE
htvcenter_SERVER_IP=$resource_htvcenterserver

# do not run on idle resources
if [ "$resource_image" == "idle" ]; then
	exit 0
fi

# set the hostname early :)
hostname $appliance_name

# also do not run before the real init of the rootfs
# if we have this file /etc/initrd-devices.conf we are still in the initrd
if [ -f /etc/initrd-devices.conf ]; then
	exit 0
fi
if [ -f /etc/debian_version ]; then
	echo "$appliance_name" > /etc/hostname
elif [ -f /etc/redhat-release ]; then
	sed -i -e "s#HOSTNAME=.*#HOSTNAME=$appliance_name#g" /etc/sysconfig/network
elif [ -f /etc/SuSE-release ]; then
	echo "$appliance_name" > /etc/HOSTNAME
fi


function role-administration_start() {
	echo "Starting the htvcenter role-administration-plugin"
	role-administration_stop 1>/dev/null 2>&1
	export FORCE_INSTALL=true
	htvcenter_install_os_dependency role-administration
	# clean up eventual left-overs, be sure we get signed
	rm -rf /etc/role-administration/ssl/* /var/lib/role-administration/ssl/* /var/lib/role-administration/state/*
	htvcenter_chkconfig del role-administration
	role-administration_stop 1>/dev/null 2>&1
	if which role-administrationd 1>/dev/null 2>&1; then
		role-administrationd -v -d -D -l syslog
	else
		echo "ERROR: Cloud not find role-administrationd binary"
	fi
}


function role-administration_stop() {
	echo "Stopping the htvcenter role-administration-plugin"
	if [ -x "/etc/init.d/role-administration" ]; then
		if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
			invoke-rc.d role-administration stop
		else
			/etc/init.d/role-administration stop
		fi
	fi
	kill -9 `ps ax | grep role-administrationd | grep -v grep | awk {' print $1 '}` 2>/dev/null
}





case "$1" in
	start)
		role-administration_start
		;;
	stop)
		role-administration_stop
		;;
	restart)
		role-administration_stop
		sleep 1
		role-administration_start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1

esac
exit $?













