#!/bin/bash
# this is the boot-service init script for the Xen-server hosts
#
# htvcenter Enterprise developed by htvcenter Enterprise GmbH.
#
# All source code and content (c) Copyright 2012, htvcenter Enterprise GmbH unless specifically noted otherwise.
#
# This source code is released under the htvcenter Enterprise Server and Client License, unless otherwise agreed with htvcenter Enterprise GmbH.
# The latest version of this license can be found here: http://htvcenter-enterprise.com/license
#
# By using this software, you acknowledge having read this license and agree to be bound thereby.
#
#           http://htvcenter-enterprise.com
#
# Copyright 2012, htvcenter Enterprise GmbH <info@htvcenter-enterprise.com>
#

htvcenter_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
# for including the package functions
export htvcenter_SOURCE_DIR="$htvcenter_SERVER_BASE_DIR/htvcenter/"
. $htvcenter_SERVER_BASE_DIR/htvcenter/include/htvcenter-functions
. $htvcenter_SERVER_BASE_DIR/htvcenter/include/htvcenter-package-functions
. $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/xen/include/htvcenter-plugin-xen-functions
. $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/xen/etc/htvcenter-plugin-xen.conf
if [ -f $htvcenter_RESOURCE_PARAMETER_FILE ]; then
	. $htvcenter_RESOURCE_PARAMETER_FILE
	htvcenter_SERVER_IP=$resource_htvcenterserver
elif [ -f $htvcenter_SERVER_BASE_DIR/htvcenter/etc/htvcenter-server.conf ]; then
	. $htvcenter_SERVER_BASE_DIR/htvcenter/etc/htvcenter-server.conf
	. $htvcenter_SERVER_BASE_DIR/htvcenter/include/htvcenter-server-functions
	htvcenter_server_get_config
	htvcenter_SERVER_IP=$htvcenter_SERVER_IP_ADDRESS
fi
htvcenter_VM_DIR="/var/lib/xen/htvcenter/"
export htvcenter_VM_DIR
# define wget to use with https
if [ "$htvcenter_web_protocol" == "https" ]; then
	WGET="wget -q --no-check-certificate"
else
	WGET="wget -q"
fi
# which screen binary to use
if [ -x /usr/bin/screen.real ]; then
	RUNSCREEN="/usr/bin/screen.real"
else
	RUNSCREEN=`which screen`
fi
# do not start on the intitrd
if [ -f /etc/initrd-devices.conf ]; then
	exit 0
fi


function xen_start() {
	echo "Starting the htvcenter xen-plugin"
	if which xm &>/dev/null; then
		chmod +x $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/xen/bin/*
		# start the vm status autostart
		if [ -d "$htvcenter_VM_DIR" ]; then
			for VM_CONFIG in `find $htvcenter_VM_DIR/* -name autostart.$resource_id 2>/dev/null`; do
				VM_NAME=`dirname $VM_CONFIG`
				VM_NAME=`basename $VM_NAME`
				XEN_VM_MAC=`cat $htvcenter_VM_DIR/$VM_NAME/mac1 2>/dev/null`
				if [ "$XEN_VM_MAC" == "" ]; then
					echo "- Could not find the MAC address of VM $VM_NAME, not autostarting..."
					continue
				fi
				# already running ?
				if ps ax | grep -i $XEN_VM_MAC | grep htvcenter-xen-monitord | grep -v grep 1>/dev/null; then
					echo "- VM $VM_NAME already running, not autostarting..."
					continue
				fi

				# ask htvcenter what to do
				if ! $WGET -O $htvcenter_VM_DIR/$VM_NAME/resource-parameter.conf "$htvcenter_web_protocol://$htvcenter_SERVER_IP/htvcenter/action/resource-monitor.php?resource_command=get_parameter&resource_mac=$XEN_VM_MAC"; then
					echo "- Could not get parameters for VM $VM_NAME, not auto-starting it ..."
					continue
				fi
				unset appliance_state
				unset image_rootdevice
				. $htvcenter_VM_DIR/$VM_NAME/resource-parameter.conf
				# is really active ?
				if [ "$appliance_state" == "active" ] && [ "$image_rootdevice" != "ram" ]; then
					echo "- Activating Rootdevice $image_rootdevice for VM $VM_NAME"
					lvchange -ay -y $image_rootdevice
					sleep 2
					# make sure the lvm device is active
					if [ -e "$image_rootdevice" ]; then
						echo "- auto-starting active VM $VM_NAME"
						# make sure the rigth device is in the VM config
						echo "phy:$image_rootdevice,hda,w" > $htvcenter_VM_DIR/$VM_NAME/disk1
						$htvcenter_SERVER_BASE_DIR/htvcenter/plugins/xen/bin/htvcenter-xen-vm start -n $VM_NAME
						sleep $htvcenter_PLUGIN_VM_AUTOSTART_DELAY
					else
						echo "- Rootdevice $image_rootdevice for VM $VM_NAME not existing, not autostarting it ..."
						continue
					fi
				else
					# make sure the VM is not still attached to the disk
					> $htvcenter_VM_DIR/$VM_NAME/disk1
					# start only the xen monitor
					echo "- auto-starting idle VM $VM_NAME"
				fi
				kill `ps ax | grep htvcenter-xen-monitord | grep -v grep | grep -i $XEN_VM_MAC | awk {' print $1 '}` 2>/dev/null
				$RUNSCREEN -dmS $XEN_VM_MAC $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/xen/sbin/htvcenter-xen-monitord $XEN_VM_MAC
			done
		fi
	fi

}


function xen_stop() {
	echo "Stopping the htvcenter xen-plugin"

}





case "$1" in
	start)
		xen_start
		;;
	stop)
		xen_stop
		;;
	restart)
		xen_stop
		sleep 1
		xen_start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1

esac
exit $?













