#!/bin/bash
# init script for the htvcenter iscsi-storage-plugin
#
# htvcenter Enterprise developed by htvcenter Enterprise GmbH.
#
# All source code and content (c) Copyright 2014, htvcenter Enterprise GmbH unless specifically noted otherwise.
#
# This source code is released under the htvcenter Enterprise Server and Client License, unless otherwise agreed with htvcenter Enterprise GmbH.
# The latest version of this license can be found here: http://htvcenter-enterprise.com/license
#
# By using this software, you acknowledge having read this license and agree to be bound thereby.
#
#           http://htvcenter-enterprise.com
#
# Copyright 2014, htvcenter Enterprise GmbH <info@htvcenter-enterprise.com>
#

htvcenter_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
. $htvcenter_SERVER_BASE_DIR/htvcenter/etc/htvcenter-server.conf
. $htvcenter_SERVER_BASE_DIR/htvcenter/include/htvcenter-functions
. $htvcenter_SERVER_BASE_DIR/htvcenter/include/htvcenter-server-functions
. $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/iscsi-storage/include/htvcenter-plugin-iscsi-storage-functions
. $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/iscsi-storage/etc/htvcenter-plugin-iscsi-storage.conf



function htvcenter_plugin_iscsi_storage_start() {
	htvcenter_plugin_iscsi_storage_stop 1>/dev/null 2>&1
	echo "Starting the htvcenter iscsi-storage-plugin"
	touch $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/base/plugins/iscsi-storage/.running
	if [ "$ISCSI_STORAGE_AUTO_START" == "yes" ]; then
		if [ -x "/etc/init.d/iscsi-target" ]; then
			if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
				invoke-rc.d iscsi-target start
			else
				/etc/init.d/iscsi-target start
			fi
		elif [ -x /etc/init.d/iscsitarget ]; then
			if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
				invoke-rc.d iscsitarget start
			else
				/etc/init.d/iscsitarget start
			fi
		fi
	fi
}


function htvcenter_plugin_iscsi_storage_stop() {
	echo "Stopping the htvcenter iscsi-storage-plugin"
	rm -f $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/base/plugins/iscsi-storage/.running
	if [ "$ISCSI_STORAGE_AUTO_START" == "yes" ]; then
		if [ -x "/etc/init.d/iscsi-target" ]; then
			if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
				invoke-rc.d iscsi-target stop
			else
				/etc/init.d/iscsi-target stop
			fi
		elif [ -x /etc/init.d/iscsitarget ]; then
			if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
				invoke-rc.d iscsitarget stop
			else
				/etc/init.d/iscsitarget stop
			fi
		fi
	fi
}

function htvcenter_plugin_iscsi_storage_uninstall() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "iscsi-storage: Please give a username to uninstall the plugin : "
		read USERNAME
		echo
		echo -n "iscsi-storage: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Uninstalling the htvcenter iscsi-storage-plugin"
	htvcenter_plugin_iscsi_storage_stop
	htvcenter_server_remove_deployment_type $USERNAME $PASSWORD iscsi-deployment
	rm -f $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/base/plugins/iscsi-storage
	rm -f $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/boot-service/root-mount.iscsi-deployment
	rm -f $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/boot-service/image.iscsi-deployment.php
	rm -f $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/boot-service/boot-service-iscsi-storage.tgz

	# remove only if lvm-storage is not enabled
	if ! ls $htvcenter_SERVER_BASE_DIR/htvcenter/web/base/plugins | grep lvm-storage 1>/dev/null 2>&1; then
		if ! ls $htvcenter_SERVER_BASE_DIR/htvcenter/web/base/plugins | grep netapp-storage 1>/dev/null 2>&1; then
			rm -f $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/boot-service/iscsid
			rm -f $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/boot-service/iscsiadm
		fi
	fi
}

function htvcenter_plugin_iscsi_storage_init() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "iscsi-storage: Please give a username to init the plugin : "
		read USERNAME
		echo
		echo -n "iscsi-storage: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Initializing the htvcenter iscsi-storage-plugin"
	htvcenter_server_add_deployment_type $USERNAME $PASSWORD iscsi-deployment iscsi-deployment "Iscsi-root deployment" iscsi-storage "Iscsi Enterprise Target Storage"
	# linking the web dir
	ln -sf $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/iscsi-storage/web $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/base/plugins/iscsi-storage
	# linking the boot-service
	ln -sf $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/iscsi-storage/web/boot-service-iscsi-storage.tgz $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/boot-service/boot-service-iscsi-storage.tgz
	# linking the root mount hook
	chmod +x $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/iscsi-storage/web/root-mount.iscsi-deployment
	ln -sf $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/iscsi-storage/web/root-mount.iscsi-deployment $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/boot-service/root-mount.iscsi-deployment
	# linking the default image-parameters
	ln -sf $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/iscsi-storage/web/image.iscsi-deployment.php $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/boot-service/image.iscsi-deployment.php

	# copying iscsid to boot-service dir
	if [ ! -x $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/boot-service/iscsid ]; then
		cp -f `which iscsid` $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/boot-service/
	fi
	# copying iscsiadm to boot-service dir
	if [ ! -x $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/boot-service/iscsiadm ]; then
		cp -f `which iscsiadm` $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/boot-service/
	fi
	# create storage dir for stat files
	mkdir -p $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/iscsi-storage/web/storage
	chmod 777 $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/iscsi-storage/web/storage
	echo "Order deny,allow" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/iscsi-storage/web/storage/.htaccess
	echo "Deny from all" >> $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/iscsi-storage/web/storage/.htaccess

}

USER=$2
PASS=$3

case "$1" in
	start)
		htvcenter_plugin_iscsi_storage_start
		;;
	stop)
		htvcenter_plugin_iscsi_storage_stop
		;;
	restart)
		htvcenter_plugin_iscsi_storage_stop
		sleep 1
		htvcenter_plugin_iscsi_storage_start
		;;
	init)
		htvcenter_plugin_iscsi_storage_init $USER $PASS
		;;
	uninstall)
		htvcenter_plugin_iscsi_storage_uninstall $USER $PASS
		;;
	*)
		echo "Usage: $0 {start|stop|restart|init|uninstall}"
		exit 1

esac
exit $?




