#!/bin/bash
# init script for the htvcenter tftpd-plugin
#
# htvcenter Enterprise developed by htvcenter Enterprise GmbH.
#
# All source code and content (c) Copyright 2014, htvcenter Enterprise GmbH unless specifically noted otherwise.
#
# This source code is released under the htvcenter Enterprise Server and Client License, unless otherwise agreed with htvcenter Enterprise GmbH.
# The latest version of this license can be found here: http://htvcenter-enterprise.com/license
#
# By using this software, you acknowledge having read this license and agree to be bound thereby.
#
#           http://htvcenter-enterprise.com
#
# Copyright 2014, htvcenter Enterprise GmbH <info@htvcenter-enterprise.com>
#

htvcenter_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
. $htvcenter_SERVER_BASE_DIR/htvcenter/etc/htvcenter-server.conf
. $htvcenter_SERVER_BASE_DIR/htvcenter/include/htvcenter-functions
. $htvcenter_SERVER_BASE_DIR/htvcenter/include/htvcenter-server-functions
. $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/tftpd/include/htvcenter-plugin-tftpd-functions
. $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/tftpd/etc/htvcenter-plugin-tftpd.conf

function htvcenter_plugin_tftpd_start() {
	echo "Starting the htvcenter tftpd-plugin"
	htvcenter_plugin_tftpd_stop 1>/dev/null 2>&1
	# check pmtu
	htvcenter_plugin_tftpd_update_pmtu

	# start tftp service
	/usr/sbin/in.tftpd -l -4 -s $htvcenter_SERVER_BASE_DIR/htvcenter/tftpboot/
	touch $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/base/plugins/tftpd/.running
}


function htvcenter_plugin_tftpd_stop() {
	echo "Stopping the htvcenter tftpd-plugin"
	killall in.tftpd 1>/dev/null 2>&1
	rm -f $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/base/plugins/tftpd/.running
}

function htvcenter_plugin_tftpd_uninstall() {
	echo "Uninstalling the htvcenter tftpd-plugin"
	htvcenter_plugin_tftpd_stop
	rm -f $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/base/plugins/tftpd
}

function htvcenter_plugin_tftpd_init() {
	echo "Initializing the htvcenter tftpd-plugin"
	# make sure tftp is not running already
	if [ -f /etc/debian_version ]; then
		if [ -x "/etc/init.d/tftpd-hpa" ]; then
			if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
				invoke-rc.d tftpd-hpa stop
			else
				/etc/init.d/tftpd-hpa stop
			fi
		fi
		# empty config to avoid start at init
		if [ -f /etc/default/tftpd-hpa ]; then
			mv -f /etc/default/tftpd-hpa /etc/default/tftpd-hpa.disabled
		fi
		update-rc.d -f tftpd-hpa remove
		# inetd ?
		if [ -f /etc/inetd.conf ]; then
			sed -i -e "s/^tftp/#tftp/g" /etc/inetd.conf
			INETDPID=`ps ax | grep inetd | grep -v grep | awk {' print $1 '}`
			kill -HUP $INETDPID 1>/dev/null 2>&1
		fi
	fi
	if [ -f /etc/xinetd.d/tftp ]; then
		sed -i -e "s/disable.*/disable = yes/" /etc/xinetd.d/tftp
		sed -i -e "s/Disable.*/Disable = yes/" /etc/xinetd.d/tftp
		if [ -x "/etc/init.d/xinetd" ]; then
			if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
				invoke-rc.d xinetd restart
			else
				/etc/init.d/xinetd restart
			fi
		fi
	fi
	# linking the web dir
	ln -sf $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/tftpd/web $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/base/plugins/tftpd
}


case "$1" in
	start)
		htvcenter_plugin_tftpd_start
		;;
	stop)
		htvcenter_plugin_tftpd_stop
		;;
	restart)
		htvcenter_plugin_tftpd_stop
		sleep 1
		htvcenter_plugin_tftpd_start
		;;
	init)
		htvcenter_plugin_tftpd_init
		;;
	uninstall)
		htvcenter_plugin_tftpd_uninstall
		;;
	*)
		echo "Usage: $0 {start|stop|restart|init|uninstall}"
		exit 1

esac
exit $?




