#!/bin/bash
# init script for the htvcenter kvm-plugin
#
# htvcenter Enterprise developed by htvcenter Enterprise GmbH.
#
# All source code and content (c) Copyright 2014, htvcenter Enterprise GmbH unless specifically noted otherwise.
#
# This source code is released under the htvcenter Enterprise Server and Client License, unless otherwise agreed with htvcenter Enterprise GmbH.
# The latest version of this license can be found here: http://htvcenter-enterprise.com/license
#
# By using this software, you acknowledge having read this license and agree to be bound thereby.
#
#           http://htvcenter-enterprise.com
#
# Copyright 2014, htvcenter Enterprise GmbH <info@htvcenter-enterprise.com>
#

htvcenter_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
. $htvcenter_SERVER_BASE_DIR/htvcenter/etc/htvcenter-server.conf
. $htvcenter_SERVER_BASE_DIR/htvcenter/include/htvcenter-functions
. $htvcenter_SERVER_BASE_DIR/htvcenter/include/htvcenter-server-functions
. $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/include/htvcenter-plugin-kvm-functions
. $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/htvcenter-plugin-kvm.conf
htvcenter_server_get_config
htvcenter_SERVER_IP=$htvcenter_SERVER_IP_ADDRESS
htvcenter_VM_DIR="/var/lib/kvm/htvcenter/"
export htvcenter_VM_DIR
htvcenter_VM_MONITOR_DIR="/var/run/htvcenter/kvm"
export resource_htvcenterserver=$htvcenter_SERVER_IP_ADDRESS
export LANG=C
# define wget to use with https
if [ "$htvcenter_WEB_PROTOCOL" == "https" ]; then
	WGET="wget -q --no-check-certificate"
else
	WGET="wget -q"
fi
# which screen binary to use
if [ -x /usr/bin/screen.real ]; then
	RUNSCREEN="/usr/bin/screen.real"
else
	RUNSCREEN=`which screen`
fi

LINE_IFS='
'

function htvcenter_plugin_kvm_start() {
	htvcenter_plugin_kvm_stop 1>/dev/null 2>&1
	echo "Starting the htvcenter kvm-plugin"
	touch $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/base/plugins/kvm/.running
	# start the vm status autostart
	if [ -d "$htvcenter_VM_DIR" ]; then
		for VM_CONFIG in `find $htvcenter_VM_DIR/* -name autostart.0 2>/dev/null`; do
			VM_NAME=`dirname $VM_CONFIG`
			VM_NAME=`basename $VM_NAME`
			. $htvcenter_VM_DIR/$VM_NAME/net1
			if ps ax | grep -i "$KVM_VM_MAC_1" | grep -v grep | grep -i screen 1>/dev/null; then
				echo "- VM $VM_NAME is running already, not auto-starting it ..."
				continue
			fi
			# ask htvcenter what to do
			if ! $WGET -O $htvcenter_VM_DIR/$VM_NAME/resource-parameter.conf "$htvcenter_WEB_PROTOCOL://$htvcenter_SERVER_IP/htvcenter/action/resource-monitor.php?resource_command=get_parameter&resource_mac=$KVM_VM_MAC_1"; then
				echo "- Could not get parameters for VM $VM_NAME, not auto-starting it ..."
				continue
			fi
			unset appliance_state
			unset image_rootdevice
			. $htvcenter_VM_DIR/$VM_NAME/resource-parameter.conf
			# is really active ?
			if [ "$appliance_state" == "active" ] && [ "$image_rootdevice" != "ram" ]; then
				echo "- Activating Rootdevice $image_rootdevice for VM $VM_NAME"
				lvchange -ay -y $image_rootdevice
				sleep 2
				# make sure the lvm device is active
				if [ -e "$image_rootdevice" ]; then
					echo "- auto-starting active VM $VM_NAME"
					# make sure the right device is in the VM config
					echo "KVM_VM_DISK_1=\"$image_rootdevice\"" > $htvcenter_VM_DIR/$VM_NAME/disk1
					$htvcenter_VM_DIR/$VM_NAME/$VM_NAME.kvm
					sleep $htvcenter_PLUGIN_VM_AUTOSTART_DELAY
				else
					echo "- Rootdevice $image_rootdevice for VM $VM_NAME not existing, not autostarting it ..."
					continue
				fi
			else
				# make sure the VM is not still attached to the disk
				echo 'KVM_VM_DISK_1=""' > $htvcenter_VM_DIR/$VM_NAME/disk1
				# start the kvm monitor
				echo "- auto-starting idle VM $VM_NAME"
			fi
			# starting the monitor for active + idle
			kill `ps ax | grep htvcenter-kvm-monitord | grep -v grep | grep -i $KVM_VM_MAC_1 | awk {' print $1 '}` 2>/dev/null
			$RUNSCREEN -dmS $KVM_VM_MAC_1 $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/sbin/htvcenter-kvm-monitord $KVM_VM_MAC_1
		done
	fi

}


function htvcenter_plugin_kvm_stop() {
	echo "Stopping the htvcenter kvm-plugin"
	rm -f $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/base/plugins/kvm/.running
}

function htvcenter_plugin_kvm_uninstall() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "kvm: Please give a username to uninstall the plugin : "
		read USERNAME
		echo
		echo -n "kvm: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Uninstalling the htvcenter kvm-plugin"
	htvcenter_plugin_kvm_stop

	# trigger init action to eventually remove cloud products
	if [ -e $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/base/plugins/cloud ]; then
		if ! wget -q $WGET_NO_CERT_CHECK -O /dev/null --http-user=$USERNAME --http-password=$PASSWORD "$htvcenter_WEB_PROTOCOL://$resource_htvcenterserver/htvcenter/base/plugins/kvm/kvm-action.php?kvm_command=uninstall"; then
			htvcenter_post_event 0 "htvcenter_plugin_kvm_start" 3 "htvcenter-plugin-kvm" "Could not trigger database hook. Please manually remove any Kvm Cloud products!"
		fi
	fi

	htvcenter_server_remove_deployment_type $USERNAME $PASSWORD kvm-lvm-deployment
	htvcenter_server_remove_deployment_type $USERNAME $PASSWORD kvm-bf-deployment
	htvcenter_server_remove_deployment_type $USERNAME $PASSWORD kvm-gluster-deployment
	htvcenter_server_remove_virtualization_type $USERNAME $PASSWORD kvm
	htvcenter_server_remove_virtualization_type $USERNAME $PASSWORD kvm-vm-local
	htvcenter_server_remove_virtualization_type $USERNAME $PASSWORD kvm-vm-net
	rm -f $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/base/plugins/kvm
	rm -f $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/boot-service/boot-service-kvm.tgz
	rm -f $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/boot-service/image.kvm-lvm-deployment.php
	rm -f $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/boot-service/image.kvm-bf-deployment.php
	rm -f $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/boot-service/image.kvm-gluster-deployment.php
	return 0

}

function htvcenter_plugin_kvm_init() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "kvm: Please give a username to init the plugin : "
		read USERNAME
		echo
		echo -n "kvm: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Initializing the htvcenter kvm-plugin"
	htvcenter_server_add_deployment_type $USERNAME $PASSWORD kvm-lvm-deployment kvm-lvm-deployment "LVM deployment for KVM" kvm "KVM LVM Storage"
	htvcenter_server_add_deployment_type $USERNAME $PASSWORD kvm-bf-deployment kvm-bf-deployment "Blockfile deployment for KVM" kvm "KVM Blockfile Storage"
	htvcenter_server_add_deployment_type $USERNAME $PASSWORD kvm-gluster-deployment kvm-gluster-deployment "Glusterfs deployment for KVM" kvm "KVM Gluster Storage"
	htvcenter_server_add_virtualization_type $USERNAME $PASSWORD kvm "KVM Host"
	htvcenter_server_add_virtualization_type $USERNAME $PASSWORD kvm-vm-local "KVM VM (localboot)"
	htvcenter_server_add_virtualization_type $USERNAME $PASSWORD kvm-vm-net "KVM VM (networkboot)"

	# linking the web dir
	ln -sf $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/web $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/base/plugins/kvm
	# link the boot-service
	ln -sf $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/web/boot-service-kvm.tgz $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/boot-service/boot-service-kvm.tgz
	# linking the image deployment parameters menu
	ln -sf $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/web/image.kvm-lvm-deployment.php $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/boot-service/image.kvm-lvm-deployment.php
	ln -sf $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/web/image.kvm-bf-deployment.php $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/boot-service/image.kvm-bf-deployment.php
	ln -sf $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/web/image.kvm-gluster-deployment.php $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/boot-service/image.kvm-gluster-deployment.php
	# create storage dir for stat files
	mkdir -p $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/web/storage
	chmod 777 $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/web/storage
	echo "Order deny,allow" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/web/storage/.htaccess
	echo "Deny from all" >> $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/web/storage/.htaccess

	# setting the kvm-ifup +kvm-ifdown script to the internal and external bridge
	# internal
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-kvm-ifup | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET1/g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-kvm-ifup-net1
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-kvm-ifdown | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET1/g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-kvm-ifdown-net1
	# external
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-kvm-ifup | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET2/g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-kvm-ifup-net2
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-kvm-ifdown | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET2/g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-kvm-ifdown-net2
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-kvm-ifup | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET3/g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-kvm-ifup-net3
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-kvm-ifdown | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET3/g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-kvm-ifdown-net3
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-kvm-ifup | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET4/g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-kvm-ifup-net4
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-kvm-ifdown | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET4/g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-kvm-ifdown-net4
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-kvm-ifup | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET5/g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-kvm-ifup-net5
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-kvm-ifdown | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET5/g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-kvm-ifdown-net5

	# ifup/down scripts for openvswitch
	# internal
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-ovs-kvm-ifup | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET1/g" | sed -e "s#@@htvcenter_SERVER_BASE_DIR@@#$htvcenter_SERVER_BASE_DIR#g" | sed -e "s#@@htvcenter_APP_NIC@@#0#g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-ovs-kvm-ifup-net1
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-ovs-kvm-ifdown | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET1/g" | sed -e "s#@@htvcenter_SERVER_BASE_DIR@@#$htvcenter_SERVER_BASE_DIR#g" | sed -e "s#@@htvcenter_APP_NIC@@#0#g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-ovs-kvm-ifdown-net1
	# external
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-ovs-kvm-ifup | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET2/g" | sed -e "s#@@htvcenter_SERVER_BASE_DIR@@#$htvcenter_SERVER_BASE_DIR#g" | sed -e "s#@@htvcenter_APP_NIC@@#1#g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-ovs-kvm-ifup-net2
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-ovs-kvm-ifdown | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET2/g" | sed -e "s#@@htvcenter_SERVER_BASE_DIR@@#$htvcenter_SERVER_BASE_DIR#g" | sed -e "s#@@htvcenter_APP_NIC@@#1#g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-ovs-kvm-ifdown-net2
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-ovs-kvm-ifup | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET3/g" | sed -e "s#@@htvcenter_SERVER_BASE_DIR@@#$htvcenter_SERVER_BASE_DIR#g" | sed -e "s#@@htvcenter_APP_NIC@@#2#g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-ovs-kvm-ifup-net3
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-ovs-kvm-ifdown | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET3/g" | sed -e "s#@@htvcenter_SERVER_BASE_DIR@@#$htvcenter_SERVER_BASE_DIR#g" | sed -e "s#@@htvcenter_APP_NIC@@#2#g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-ovs-kvm-ifdown-net3
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-ovs-kvm-ifup | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET4/g" | sed -e "s#@@htvcenter_SERVER_BASE_DIR@@#$htvcenter_SERVER_BASE_DIR#g" | sed -e "s#@@htvcenter_APP_NIC@@#3#g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-ovs-kvm-ifup-net4
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-ovs-kvm-ifdown | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET4/g" | sed -e "s#@@htvcenter_SERVER_BASE_DIR@@#$htvcenter_SERVER_BASE_DIR#g" | sed -e "s#@@htvcenter_APP_NIC@@#3#g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-ovs-kvm-ifdown-net4
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-ovs-kvm-ifup | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET5/g" | sed -e "s#@@htvcenter_SERVER_BASE_DIR@@#$htvcenter_SERVER_BASE_DIR#g" | sed -e "s#@@htvcenter_APP_NIC@@#4#g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-ovs-kvm-ifup-net5
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-ovs-kvm-ifdown | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET5/g" | sed -e "s#@@htvcenter_SERVER_BASE_DIR@@#$htvcenter_SERVER_BASE_DIR#g" | sed -e "s#@@htvcenter_APP_NIC@@#4#g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-ovs-kvm-ifdown-net5
	chmod +x $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/*

	# ifup/down scripts for bridged vlans
	# internal
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-vlan-kvm-ifup | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET1/g" | sed -e "s#@@htvcenter_SERVER_BASE_DIR@@#$htvcenter_SERVER_BASE_DIR#g" | sed -e "s#@@htvcenter_APP_NIC@@#0#g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-vlan-kvm-ifup-net1
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-vlan-kvm-ifdown | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET1/g" | sed -e "s#@@htvcenter_SERVER_BASE_DIR@@#$htvcenter_SERVER_BASE_DIR#g" | sed -e "s#@@htvcenter_APP_NIC@@#0#g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-vlan-kvm-ifdown-net1
	# external
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-vlan-kvm-ifup | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET2/g" | sed -e "s#@@htvcenter_SERVER_BASE_DIR@@#$htvcenter_SERVER_BASE_DIR#g" | sed -e "s#@@htvcenter_APP_NIC@@#1#g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-vlan-kvm-ifup-net2
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-vlan-kvm-ifdown | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET2/g" | sed -e "s#@@htvcenter_SERVER_BASE_DIR@@#$htvcenter_SERVER_BASE_DIR#g" | sed -e "s#@@htvcenter_APP_NIC@@#1#g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-vlan-kvm-ifdown-net2
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-vlan-kvm-ifup | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET3/g" | sed -e "s#@@htvcenter_SERVER_BASE_DIR@@#$htvcenter_SERVER_BASE_DIR#g" | sed -e "s#@@htvcenter_APP_NIC@@#2#g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-vlan-kvm-ifup-net3
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-vlan-kvm-ifdown | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET3/g" | sed -e "s#@@htvcenter_SERVER_BASE_DIR@@#$htvcenter_SERVER_BASE_DIR#g" | sed -e "s#@@htvcenter_APP_NIC@@#2#g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-vlan-kvm-ifdown-net3
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-vlan-kvm-ifup | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET4/g" | sed -e "s#@@htvcenter_SERVER_BASE_DIR@@#$htvcenter_SERVER_BASE_DIR#g" | sed -e "s#@@htvcenter_APP_NIC@@#3#g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-vlan-kvm-ifup-net4
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-vlan-kvm-ifdown | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET4/g" | sed -e "s#@@htvcenter_SERVER_BASE_DIR@@#$htvcenter_SERVER_BASE_DIR#g" | sed -e "s#@@htvcenter_APP_NIC@@#3#g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-vlan-kvm-ifdown-net4
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-vlan-kvm-ifup | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET5/g" | sed -e "s#@@htvcenter_SERVER_BASE_DIR@@#$htvcenter_SERVER_BASE_DIR#g" | sed -e "s#@@htvcenter_APP_NIC@@#4#g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-vlan-kvm-ifup-net5
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-vlan-kvm-ifdown | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET5/g" | sed -e "s#@@htvcenter_SERVER_BASE_DIR@@#$htvcenter_SERVER_BASE_DIR#g" | sed -e "s#@@htvcenter_APP_NIC@@#4#g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-vlan-kvm-ifdown-net5
	chmod +x $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/*

	# create kvm-stat dir
	mkdir -p $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/web/kvm-stat
	chmod -R 777 $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/web/kvm-stat
	echo "Order deny,allow" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/web/kvm-stat/.htaccess
	echo "Deny from all" >> $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/web/kvm-stat/.htaccess

	# trigger init action to eventually add cloud products
	if [ -e $htvcenter_WEBSERVER_DOCUMENT_ROOT/htvcenter/base/plugins/cloud ]; then
		if ! wget -q $WGET_NO_CERT_CHECK -O /dev/null --http-user=$USERNAME --http-password=$PASSWORD "$htvcenter_WEB_PROTOCOL://$resource_htvcenterserver/htvcenter/base/plugins/kvm/kvm-action.php?kvm_command=init"; then
			htvcenter_post_event 0 "htvcenter_plugin_kvm_start" 3 "htvcenter-plugin-kvm" "Could not trigger database hook. Please manually add Kvm Cloud products!"
		fi
	fi
	return 0
}

USER=$2
PASS=$3

case "$1" in
	start)
		htvcenter_plugin_kvm_start
		;;
	stop)
		htvcenter_plugin_kvm_stop
		;;
	restart)
		htvcenter_plugin_kvm_stop
		sleep 1
		htvcenter_plugin_kvm_start
		;;
	init)
		htvcenter_plugin_kvm_init $USER $PASS
		;;
	uninstall)
		htvcenter_plugin_kvm_uninstall $USER $PASS
		;;
	*)
		echo "Usage: $0 {start|stop|restart|init|uninstall}"
		exit 1

esac
exit $?




