#!/bin/bash
# this is the boot-service init script for the Kvm-server hosts
#
# htvcenter Enterprise developed by htvcenter Enterprise GmbH.
#
# All source code and content (c) Copyright 2014, htvcenter Enterprise GmbH unless specifically noted otherwise.
#
# This source code is released under the htvcenter Enterprise Server and Client License, unless otherwise agreed with htvcenter Enterprise GmbH.
# The latest version of this license can be found here: http://htvcenter-enterprise.com/license
#
# By using this software, you acknowledge having read this license and agree to be bound thereby.
#
#           http://htvcenter-enterprise.com
#
# Copyright 2014, htvcenter Enterprise GmbH <info@htvcenter-enterprise.com>
#

htvcenter_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
# for including the package functions
export htvcenter_SOURCE_DIR="$htvcenter_SERVER_BASE_DIR/htvcenter/"
. $htvcenter_SERVER_BASE_DIR/htvcenter/include/htvcenter-functions
. $htvcenter_SERVER_BASE_DIR/htvcenter/include/htvcenter-package-functions
. $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/include/htvcenter-plugin-kvm-functions
. $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/htvcenter-plugin-kvm.conf
if [ -f $htvcenter_RESOURCE_PARAMETER_FILE ]; then
	. $htvcenter_RESOURCE_PARAMETER_FILE
	htvcenter_SERVER_IP=$resource_htvcenterserver
elif [ -f $htvcenter_SERVER_BASE_DIR/htvcenter/etc/htvcenter-server.conf ]; then
	. $htvcenter_SERVER_BASE_DIR/htvcenter/etc/htvcenter-server.conf
	. $htvcenter_SERVER_BASE_DIR/htvcenter/include/htvcenter-server-functions
	htvcenter_server_get_config
	htvcenter_SERVER_IP=$htvcenter_SERVER_IP_ADDRESS
fi
htvcenter_VM_DIR="/var/lib/kvm/htvcenter/"
export htvcenter_VM_DIR
htvcenter_VM_MONITOR_DIR="/var/run/htvcenter/kvm"
# define wget to use with https
if [ "$htvcenter_web_protocol" == "https" ]; then
	WGET="wget -q --no-check-certificate"
else
	WGET="wget -q"
fi
# which screen binary to use
if [ -x /usr/bin/screen.real ]; then
	RUNSCREEN="/usr/bin/screen.real"
else
	RUNSCREEN=`which screen`
fi

# do not start on the intitrd
if [ -f /etc/initrd-devices.conf ]; then
	exit 0
fi


function kvm_start() {
	echo "Starting the htvcenter kvm-plugin"
	# preparing the nic-bios in case the htvcenter server itself is the kvm-host
	if [ ! -d /usr/share/kvm/ ]; then
		mkdir -p /usr/share/kvm
	fi
	# be sure to have the tun device
	if [ ! -e /dev/tun ]; then
		mknod /dev/tun c 10 200
	fi
	depmod -a
	modprobe tun
	# setting the kvm-ifup +kvm-ifdown script to the internal and external bridge
	# internal
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-kvm-ifup | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET1/g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-kvm-ifup-net1
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-kvm-ifdown | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET1/g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-kvm-ifdown-net1
	# external
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-kvm-ifup | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET2/g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-kvm-ifup-net2
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-kvm-ifdown | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET2/g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-kvm-ifdown-net2
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-kvm-ifup | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET3/g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-kvm-ifup-net3
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-kvm-ifdown | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET3/g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-kvm-ifdown-net3
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-kvm-ifup | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET4/g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-kvm-ifup-net4
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-kvm-ifdown | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET4/g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-kvm-ifdown-net4
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-kvm-ifup | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET5/g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-kvm-ifup-net5
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-kvm-ifdown | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET5/g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-kvm-ifdown-net5
	# ifup/down scripts for openvswitch
	# internal
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-ovs-kvm-ifup | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET1/g" | sed -e "s#@@htvcenter_SERVER_BASE_DIR@@#$htvcenter_SERVER_BASE_DIR#g" | sed -e "s#@@htvcenter_APP_NIC@@#0#g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-ovs-kvm-ifup-net1
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-ovs-kvm-ifdown | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET1/g" | sed -e "s#@@htvcenter_SERVER_BASE_DIR@@#$htvcenter_SERVER_BASE_DIR#g" | sed -e "s#@@htvcenter_APP_NIC@@#0#g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-ovs-kvm-ifdown-net1
	# external
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-ovs-kvm-ifup | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET2/g" | sed -e "s#@@htvcenter_SERVER_BASE_DIR@@#$htvcenter_SERVER_BASE_DIR#g" | sed -e "s#@@htvcenter_APP_NIC@@#1#g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-ovs-kvm-ifup-net2
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-ovs-kvm-ifdown | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET2/g" | sed -e "s#@@htvcenter_SERVER_BASE_DIR@@#$htvcenter_SERVER_BASE_DIR#g" | sed -e "s#@@htvcenter_APP_NIC@@#1#g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-ovs-kvm-ifdown-net2
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-ovs-kvm-ifup | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET3/g" | sed -e "s#@@htvcenter_SERVER_BASE_DIR@@#$htvcenter_SERVER_BASE_DIR#g" | sed -e "s#@@htvcenter_APP_NIC@@#2#g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-ovs-kvm-ifup-net3
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-ovs-kvm-ifdown | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET3/g" | sed -e "s#@@htvcenter_SERVER_BASE_DIR@@#$htvcenter_SERVER_BASE_DIR#g" | sed -e "s#@@htvcenter_APP_NIC@@#2#g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-ovs-kvm-ifdown-net3
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-ovs-kvm-ifup | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET4/g" | sed -e "s#@@htvcenter_SERVER_BASE_DIR@@#$htvcenter_SERVER_BASE_DIR#g" | sed -e "s#@@htvcenter_APP_NIC@@#3#g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-ovs-kvm-ifup-net4
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-ovs-kvm-ifdown | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET4/g" | sed -e "s#@@htvcenter_SERVER_BASE_DIR@@#$htvcenter_SERVER_BASE_DIR#g" | sed -e "s#@@htvcenter_APP_NIC@@#3#g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-ovs-kvm-ifdown-net4
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-ovs-kvm-ifup | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET5/g" | sed -e "s#@@htvcenter_SERVER_BASE_DIR@@#$htvcenter_SERVER_BASE_DIR#g" | sed -e "s#@@htvcenter_APP_NIC@@#4#g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-ovs-kvm-ifup-net5
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-ovs-kvm-ifdown | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET5/g" | sed -e "s#@@htvcenter_SERVER_BASE_DIR@@#$htvcenter_SERVER_BASE_DIR#g" | sed -e "s#@@htvcenter_APP_NIC@@#4#g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-ovs-kvm-ifdown-net5

	# ifup/down scripts for bridged vlans
	# internal
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-vlan-kvm-ifup | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET1/g" | sed -e "s#@@htvcenter_SERVER_BASE_DIR@@#$htvcenter_SERVER_BASE_DIR#g" | sed -e "s#@@htvcenter_APP_NIC@@#0#g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-vlan-kvm-ifup-net1
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-vlan-kvm-ifdown | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET1/g" | sed -e "s#@@htvcenter_SERVER_BASE_DIR@@#$htvcenter_SERVER_BASE_DIR#g" | sed -e "s#@@htvcenter_APP_NIC@@#0#g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-vlan-kvm-ifdown-net1
	# external
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-vlan-kvm-ifup | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET2/g" | sed -e "s#@@htvcenter_SERVER_BASE_DIR@@#$htvcenter_SERVER_BASE_DIR#g" | sed -e "s#@@htvcenter_APP_NIC@@#1#g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-vlan-kvm-ifup-net2
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-vlan-kvm-ifdown | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET2/g" | sed -e "s#@@htvcenter_SERVER_BASE_DIR@@#$htvcenter_SERVER_BASE_DIR#g" | sed -e "s#@@htvcenter_APP_NIC@@#1#g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-vlan-kvm-ifdown-net2
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-vlan-kvm-ifup | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET3/g" | sed -e "s#@@htvcenter_SERVER_BASE_DIR@@#$htvcenter_SERVER_BASE_DIR#g" | sed -e "s#@@htvcenter_APP_NIC@@#2#g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-vlan-kvm-ifup-net3
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-vlan-kvm-ifdown | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET3/g" | sed -e "s#@@htvcenter_SERVER_BASE_DIR@@#$htvcenter_SERVER_BASE_DIR#g" | sed -e "s#@@htvcenter_APP_NIC@@#2#g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-vlan-kvm-ifdown-net3
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-vlan-kvm-ifup | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET4/g" | sed -e "s#@@htvcenter_SERVER_BASE_DIR@@#$htvcenter_SERVER_BASE_DIR#g" | sed -e "s#@@htvcenter_APP_NIC@@#3#g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-vlan-kvm-ifup-net4
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-vlan-kvm-ifdown | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET4/g" | sed -e "s#@@htvcenter_SERVER_BASE_DIR@@#$htvcenter_SERVER_BASE_DIR#g" | sed -e "s#@@htvcenter_APP_NIC@@#3#g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-vlan-kvm-ifdown-net4
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-vlan-kvm-ifup | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET5/g" | sed -e "s#@@htvcenter_SERVER_BASE_DIR@@#$htvcenter_SERVER_BASE_DIR#g" | sed -e "s#@@htvcenter_APP_NIC@@#4#g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-vlan-kvm-ifup-net5
	cat $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/etc/templates/htvcenter-vlan-kvm-ifdown | sed -e "s/@@htvcenter_PLUGIN_KVM_BRIDGE@@/$htvcenter_PLUGIN_KVM_BRIDGE_NET5/g" | sed -e "s#@@htvcenter_SERVER_BASE_DIR@@#$htvcenter_SERVER_BASE_DIR#g" | sed -e "s#@@htvcenter_APP_NIC@@#4#g" > $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/htvcenter-vlan-kvm-ifdown-net5

	chmod +x $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/bin/*

	# make sure the kvm modules are loaded
	modprobe kvm
	if grep flags.*vmx /proc/cpuinfo 1>/dev/null; then modprobe kvm-intel; fi
	if grep flags.*svm /proc/cpuinfo 1>/dev/null; then modprobe kvm-amd; fi

	# start the vm status autostart
	if [ -d "$htvcenter_VM_DIR" ]; then
		for VM_CONFIG in `find $htvcenter_VM_DIR/* -name autostart.$resource_id 2>/dev/null`; do
			VM_NAME=`dirname $VM_CONFIG`
			VM_NAME=`basename $VM_NAME`
			. $htvcenter_VM_DIR/$VM_NAME/net1
			if ps ax | grep -i "$KVM_VM_MAC_1" | grep -v grep | grep -i screen 1>/dev/null; then
				echo "- VM $VM_NAME is running already, not auto-starting it ..."
				continue
			fi
			# ask htvcenter what to do
			if ! $WGET -O $htvcenter_VM_DIR/$VM_NAME/resource-parameter.conf "$htvcenter_web_protocol://$htvcenter_SERVER_IP/htvcenter/action/resource-monitor.php?resource_command=get_parameter&resource_mac=$KVM_VM_MAC_1"; then
				echo "- Could not get parameters for VM $VM_NAME, not auto-starting it ..."
				continue
			fi
			unset appliance_state
			unset image_rootdevice
			. $htvcenter_VM_DIR/$VM_NAME/resource-parameter.conf
			# is really active ?
			if [ "$appliance_state" == "active" ] && [ "$image_rootdevice" != "ram" ]; then
				echo "- Activating Rootdevice $image_rootdevice for VM $VM_NAME"
				lvchange -ay -y $image_rootdevice
				sleep 2
				# make sure the lvm device is active
				if [ -e "$image_rootdevice" ]; then
					echo "- auto-starting active VM $VM_NAME"
					# make sure the rigth device is in the VM config
					echo "KVM_VM_DISK_1=\"$image_rootdevice\"" > $htvcenter_VM_DIR/$VM_NAME/disk1
					$htvcenter_VM_DIR/$VM_NAME/$VM_NAME.kvm
					sleep $htvcenter_PLUGIN_VM_AUTOSTART_DELAY
				else
					echo "- Rootdevice $image_rootdevice for VM $VM_NAME not existing, not autostarting it ..."
					continue
				fi
			else
				# make sure the VM is not still attached to the disk
				echo 'KVM_VM_DISK_1=""' > $htvcenter_VM_DIR/$VM_NAME/disk1
				# start the kvm monitor
				echo "- auto-starting idle VM $VM_NAME"
			fi
			# starting the monitor for active + idle
			kill `ps ax | grep htvcenter-kvm-monitord | grep -v grep | grep -i $KVM_VM_MAC_1 | awk {' print $1 '}` 2>/dev/null
			$RUNSCREEN -dmS $KVM_VM_MAC_1 $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/kvm/sbin/htvcenter-kvm-monitord $KVM_VM_MAC_1
		done
	fi

}


function kvm_stop() {
	echo "Stopping the htvcenter kvm-plugin"
	# by default we do not stop the active VMs, otherwise htvcenter-client restart would restart VMs
#	if [ -d "$htvcenter_VM_DIR" ]; then
#		for VM_CONFIG in `find $htvcenter_VM_DIR/* -name autostart.$resource_id 2>/dev/null`; do
#			VM_NAME=`dirname $VM_CONFIG`
#			VM_NAME=`basename $VM_NAME`
#			if [ -e "$htvcenter_VM_MONITOR_DIR/kvm.$VM_NAME.mon" ]; then
#				echo "- Stopping VM $VM_NAME"
#				echo "system_powerdown" | socat stdio unix:$htvcenter_VM_MONITOR_DIR/kvm.$VM_NAME.mon
#			fi
#		done
#	fi




}





case "$1" in
	start)
		kvm_start
		;;
	stop)
		kvm_stop
		;;
	restart)
		kvm_stop
		sleep 1
		kvm_start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1

esac
exit $?













