#!/bin/bash
# init script for the htvcenter wakeuponlan-plugin
#
# htvcenter Enterprise developed by htvcenter Enterprise GmbH.
#
# All source code and content (c) Copyright 2014, htvcenter Enterprise GmbH unless specifically noted otherwise.
#
# This source code is released under the htvcenter Enterprise Server and Client License, unless otherwise agreed with htvcenter Enterprise GmbH.
# The latest version of this license can be found here: http://htvcenter-enterprise.com/license
#
# By using this software, you acknowledge having read this license and agree to be bound thereby.
#
#           http://htvcenter-enterprise.com
#
# Copyright 2014, htvcenter Enterprise GmbH <info@htvcenter-enterprise.com>


htvcenter_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
export htvcenter_SOURCE_DIR="$htvcenter_SERVER_BASE_DIR/htvcenter/"
. $htvcenter_SERVER_BASE_DIR/htvcenter/include/htvcenter-functions
. $htvcenter_SERVER_BASE_DIR/htvcenter/include/htvcenter-package-functions
. $htvcenter_SERVER_BASE_DIR/htvcenter/plugins/wakeuponlan/include/htvcenter-plugin-wakeuponlan-functions
if [ -f $htvcenter_RESOURCE_PARAMETER_FILE ]; then
	. $htvcenter_RESOURCE_PARAMETER_FILE
	htvcenter_SERVER_IP=$resource_htvcenterserver
elif [ -f $htvcenter_SERVER_BASE_DIR/htvcenter/etc/htvcenter-server.conf ]; then
	. $htvcenter_SERVER_BASE_DIR/htvcenter/etc/htvcenter-server.conf
	. $htvcenter_SERVER_BASE_DIR/htvcenter/include/htvcenter-server-functions
	htvcenter_server_get_config
	htvcenter_SERVER_IP=$htvcenter_SERVER_IP_ADDRESS
fi
IP_MGMT_CONFIG_DIR=`dirname $htvcenter_RESOURCE_PARAMETER_FILE`

# define wget to use with https
if [ "$htvcenter_web_protocol" == "https" ]; then
	export WGET="wget --no-check-certificate -q"
else
	export WGET="wget -q"
fi

# only start in the initrd when we have ethtool availalbe
if [ -f /etc/initrd-devices.conf ]; then
	if ! which ethtool 1>/ethtool.log; then
		rm -f /ethtool.log
		exit 0
	else
		rm -f /ethtool.log
	fi
else
	if ! which ethtool 1>/dev/null; then
		export FORCE_INSTALL=true
		htvcenter_install_os_dependency ethtool
	fi
fi


function wakeuponlan_start() {
	echo "Starting the htvcenter wakeuponlan plugin"
	htvcenter_INTERFACE=`ifconfig | grep -i $resource_mac | grep :oq | cut -d':' -f1`
	if [ "$htvcenter_INTERFACE" != "" ]; then
		ethtool -s $htvcenter_INTERFACE wol g 2>/ethtool.log
		rm -f /ethtool.log
		echo "- enabled Wake-up-on-LAN on interface $htvcenter_INTERFACE"
	fi
}


function wakeuponlan_stop() {
	echo "Stopping the htvcenter wakeuponlan plugin"

}



case "$1" in
	start)
		wakeuponlan_start
		;;
	stop)
		wakeuponlan_stop
		;;
	restart)
		wakeuponlan_start
		sleep 1
		wakeuponlan_stop
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1

esac
exit $?













